// Auto-generated from Bíblia dos Hooks 2 (PDF) - 949 hooks traduzidos para PT-BR
export type BibliaCategory = 'lista' | 'dor' | 'historia' | 'revelacao' | 'urgencia' | 'curiosidade' | 'experiencia' | 'tutorial' | 'autoridade';

export interface BibliaHook { id: number; text: string; category: BibliaCategory; }

export const BIBLIA_CATEGORIES: { id: BibliaCategory; label: string; emoji: string; objetivo: string }[] = [
  { id: 'lista', label: 'Listas', emoji: '📋', objetivo: 'Entregar valor escaneável e prender atenção com promessa numérica clara.' },
  { id: 'dor', label: 'Dor', emoji: '💔', objetivo: 'Ativar identificação imediata com um problema que o público vive.' },
  { id: 'historia', label: 'Histórias', emoji: '📖', objetivo: 'Criar conexão emocional e retenção através de narrativa pessoal.' },
  { id: 'revelacao', label: 'Revelação', emoji: '🔓', objetivo: 'Quebrar crença comum e expor um segredo/insight pouco conhecido.' },
  { id: 'urgencia', label: 'Urgência', emoji: '⚡', objetivo: 'Provocar ação imediata usando escassez, tempo ou risco de perda.' },
  { id: 'curiosidade', label: 'Curiosidade', emoji: '🤔', objetivo: 'Abrir loop mental que obriga o espectador a continuar assistindo.' },
  { id: 'experiencia', label: 'Experiência', emoji: '🧪', objetivo: 'Gerar prova social mostrando resultado real de um teste vivido.' },
  { id: 'tutorial', label: 'Tutorial', emoji: '🎯', objetivo: 'Prometer um passo a passo prático e replicável para um resultado.' },
  { id: 'autoridade', label: 'Autoridade', emoji: '👑', objetivo: 'Posicionar o criador como referência confiável no nicho.' },
];

export const BIBLIA_HOOKS: BibliaHook[] = [
  { id: 1, text: `Eu experimentei todo (ex: suplemento para emagrecer) que existe e aqui estão os resultados…`, category: 'experiencia' },
  { id: 2, text: `O que eu pedi vs. o que eu recebi`, category: 'autoridade' },
  { id: 3, text: `O TikTok me fez comprar isso`, category: 'autoridade' },
  { id: 4, text: `O (ex: pai de primeira viagem) perfeito não existe`, category: 'autoridade' },
  { id: 5, text: `(ex: certas estratégias de growth hacking) são tão bom para (ex: o crescimento rápido de uma startup) que foram banido`, category: 'autoridade' },
  { id: 6, text: `Você já passou por (ex: endividamento por compras impulsivas)? Veja como nunca mais fazer isso…`, category: 'curiosidade' },
  { id: 7, text: `Quer (ex: uma pele radiante em 30 dias)? Então pare de rolar`, category: 'dor' },
  { id: 8, text: `Se você ainda não experimentou… Assista a isso!`, category: 'autoridade' },
  { id: 9, text: `Se você não faz (ex: a técnica de congelamento de refeições), está perdendo`, category: 'dor' },
  { id: 10, text: `Pare de rolar se você sofre de (ex: dores crônicas nas costas)`, category: 'dor' },
  { id: 11, text: `Por que ninguém está falando sobre dicas de (ex: como viajar mais barato para destinos exóticos)?`, category: 'revelacao' },
  { id: 12, text: `Coisas que eu gostaria de saber mais cedo Parte (ex: 5)`, category: 'autoridade' },
  { id: 13, text: `Este é um mito menos conhecido, mas muito prejudicial na indústria de (ex: vendas online)`, category: 'autoridade' },
  { id: 14, text: `Este truque vai te economizar horas em (ex: organização de projetos)`, category: 'autoridade' },
  { id: 15, text: `Isso pode me cancelar, mas vou te contar (ex: a verdade sobre o amor à primeira vista)…`, category: 'autoridade' },
  { id: 16, text: `Você provavelmente não sabia disso, mas (ex: 80% dos clientes compram por impulso emocional)…`, category: 'autoridade' },
  { id: 17, text: `A única maneira de fazer (ex: um agachamento perfeito e sem lesões)…`, category: 'autoridade' },
  { id: 18, text: `Não (ex: invista em criptomoedas) até ler isso`, category: 'autoridade' },
  { id: 19, text: `Vamos resolver o debate de longa data…`, category: 'autoridade' },
  { id: 20, text: `Sou só eu ou (ex: todo mundo está viciado em podcasts ultimamente)`, category: 'autoridade' },
  { id: 21, text: `VOCÊ PRECISA deste (ex: plano alimentar personalizado) se quiser (ex: perder 10kg em 2 meses)...`, category: 'autoridade' },
  { id: 22, text: `Decifrei o código de (ex: crescer no Instagram organicamente)…`, category: 'autoridade' },
  { id: 23, text: `3 coisas que eu gostaria de saber antes de (ex: ter meu primeiro filho)`, category: 'lista' },
  { id: 24, text: `3 coisas que você precisa parar de fazer agora mesmo`, category: 'lista' },
  { id: 25, text: `5 coisas que você não sabia sobre (ex: inteligência artificial)`, category: 'lista' },
  { id: 26, text: `Você sabia que (ex: 85%) de (ex: estudantes universitários) acreditam em (ex: que um diploma garante sucesso financeiro)?`, category: 'curiosidade' },
  { id: 27, text: `Você sabia que (ex: o ponto mais profundo do oceano é mais profundo que o Monte Everest é alto)?`, category: 'curiosidade' },
  { id: 28, text: `Você sabia que (ex: 70% dos casais) lutam com (ex: a comunicação aberta sobre finanças)?`, category: 'curiosidade' },
  { id: 29, text: `Você sabia que (ex: mais plástico é jogado no oceano a cada ano do que o peso combinado de todos os animais terrestres)?`, category: 'curiosidade' },
  { id: 30, text: `Todo mundo está falando sobre essa nova (ex: rotina de skin care minimalista).`, category: 'autoridade' },
  { id: 31, text: `Você já notou que (ex: Érico Rocha) (ex: sempre usa gatilhos mentais em suas vendas)? Eis o porquê...`, category: 'curiosidade' },
  { id: 32, text: `Eu consigo saber se alguém é (ex: ambicioso e focado) em (ex: 5) minutos depois de conhecê-lo(a)...`, category: 'autoridade' },
  { id: 33, text: `Quer saber a peça que falta no seu (ex: funil de vendas)?`, category: 'autoridade' },
  { id: 34, text: `Você conhece o segredo para (ex: ganhar massa muscular de forma eficiente)?`, category: 'revelacao' },
  { id: 35, text: `Você quer saber como dobrar suas economias este ano?`, category: 'tutorial' },
  { id: 36, text: `Você quer saber como (ex: fazer um bolo perfeito sem glúten)?`, category: 'tutorial' },
  { id: 37, text: `Já se perguntou como (ex: o algoritmo do TikTok) funciona?`, category: 'curiosidade' },
  { id: 38, text: `Já se perguntou por que (ex: seu bebê chora sem motivo aparente à noite)? eis a resposta…`, category: 'curiosidade' },
  { id: 39, text: `Tenho novidades para você – (ex: viajar sozinho é a melhor forma de se conhecer) ...`, category: 'dor' },
  { id: 40, text: `E se eu te dissesse que (ex: a maioria das estratégias de marketing digital que você conhece está desatualizada) ...`, category: 'dor' },
  { id: 41, text: `Aqui está o que ninguém te conta sobre {insira um objetivo} 👇`, category: 'revelacao' },
  { id: 42, text: `Quer roubar meu método comprovado de {insira um nome} para {insira um objetivo}? 🔥`, category: 'tutorial' },
  { id: 43, text: `Eu nunca percebi [algo] até experimentar [experiência]...`, category: 'autoridade' },
  { id: 44, text: `Eu nunca percebi que ___ poderia ser tão simples.`, category: 'autoridade' },
  { id: 45, text: `Eu nunca percebi isso sobre [tópico] até agora.`, category: 'urgencia' },
  { id: 46, text: `Eu nunca pensei que [produto/serviço] funcionaria para [problema], mas...`, category: 'autoridade' },
  { id: 47, text: `Eu nunca pensei que [resultado inesperado] aconteceria.`, category: 'autoridade' },
  { id: 48, text: `Eu nunca pensei que ___ poderia ser tão fácil.`, category: 'autoridade' },
  { id: 49, text: `Eu nunca pensei que diria isso, mas [declaração inesperada]...`, category: 'autoridade' },
  { id: 50, text: `Eu prometo que você nunca viu nada assim antes!`, category: 'autoridade' },
  { id: 51, text: `fiquei espantado(a) quando descobri isto sobre [tópico]...`, category: 'autoridade' },
  { id: 52, text: `fiquei chocado(a) quando descobri [fato] sobre [tópico]...`, category: 'autoridade' },
  { id: 53, text: `fiquei chocado(a) quando descobri [fato].`, category: 'autoridade' },
  { id: 54, text: `fiquei surpreso(a) ao descobrir que [fato]...`, category: 'autoridade' },
  { id: 55, text: `fiquei surpreso(a) ao aprender [fato].`, category: 'autoridade' },
  { id: 56, text: `A Solução de {#} Minutos, {#} Passos Para o Melhor {Substantivo}`, category: 'autoridade' },
  { id: 57, text: `aqui está uma pílula difícil que [público-alvo] não consegue engolir…`, category: 'autoridade' },
  { id: 58, text: `aqui está um truque que ninguém te conta sobre [tópico]…`, category: 'revelacao' },
  { id: 59, text: `é assim que eu alcancei [resultado desejado] em [período de tempo].`, category: 'autoridade' },
  { id: 60, text: `é assim que você torna [algo complicado] mais fácil…`, category: 'autoridade' },
  { id: 61, text: `aqui está a verdade oculta sobre (ex: por que alguns casamentos fracassam rapidamente).`, category: 'revelacao' },
  { id: 62, text: `é isto que eu descobri sobre (ex: o algoritmo do Instagram em 2024)…`, category: 'autoridade' },
  { id: 63, text: `é isto que ninguém te conta sobre (ex: o verdadeiro impacto do açúcar na sua performance atlética).`, category: 'revelacao' },
  { id: 64, text: `aqui está uma forma (ex: fácil) de (ex: aprender um novo idioma em 3 meses).`, category: 'autoridade' },
  { id: 65, text: `aqui está um (ex: segredo de programação) sobre (ex: a origem do Wi-Fi).`, category: 'autoridade' },
  { id: 66, text: `aqui está um plano de (ex: 7) dias para (ex: dobrar suas vendas online).`, category: 'autoridade' },
  { id: 67, text: `aqui está o que (ex: a Kylie Jenner) não te conta sobre (ex: os filtros que ela usa para ter pele perfeita).`, category: 'dor' },
  { id: 68, text: `aqui está o que aconteceu depois que eu experimentei (ex: cozinhar todas as minhas refeições com uma Airfryer por uma semana)`, category: 'historia' },
  { id: 69, text: `aqui está o que acontece quando você (ex: deixar seu filho decidir o que comer no jantar todos os dias).`, category: 'autoridade' },
  { id: 70, text: `é por isso que (ex: "apenas trabalhe mais horas" para ser produtivo) não funciona.`, category: 'autoridade' },
  { id: 71, text: `é por isso que (ex: beber sucos detox todos os dias) é na verdade prejudicial.`, category: 'autoridade' },
  { id: 72, text: `é por isso que (ex: o storytelling em suas copies) é um divisor de águas.`, category: 'autoridade' },
  { id: 73, text: `é por isso que (ex: planejar sua rota de viagem com antecedência) é mais importante do que você pensa.`, category: 'autoridade' },
  { id: 74, text: `é por isso que eu troquei de (ex: iPhone para Android) para (ex: um Galaxy S24).`, category: 'autoridade' },
  { id: 75, text: `aposto que você não sabia disto sobre (ex: a água da torneira da sua casa).`, category: 'autoridade' },
  { id: 76, text: `eu tinha essa idade hoje quando descobri…`, category: 'urgencia' },
  { id: 77, text: `eu tinha essa idade hoje quando aprendi isso…`, category: 'urgencia' },
  { id: 78, text: `eu não ia compartilhar isso, mas não resisti: siga com um fato ou revelação surpreendente.`, category: 'autoridade' },
  { id: 79, text: `queria que alguém tivesse me dito isso quando estava começando como (ex: um empreendedor digital).`, category: 'tutorial' },
  { id: 80, text: `vou te contar um segredo que ninguém nunca te contou sobre (ex: como escrever títulos que convertem 10x mais).`, category: 'revelacao' },
  { id: 81, text: `se uma situação louca (eu estava no corredor da morte, minha casa estava pegando fogo) eu faria (ex: sacrificaria meu tempo livre para ensinar meu filho a programar).`, category: 'dor' },
  { id: 82, text: `se você não sabe, agora sabe!`, category: 'urgencia' },
  { id: 83, text: `se você acha que (ex: fazer apenas cardio) é melhor que (ex: combinar treino de força e cardio para perda de peso), vou provar que você está errado agora mesmo.`, category: 'urgencia' },
  { id: 84, text: `se você acha (ex: que criptomoedas é só para geeks), espere até ver isso…`, category: 'autoridade' },
  { id: 85, text: `se você quer (ex: ter liberdade financeira antes dos 40), comece com isso…`, category: 'autoridade' },
  { id: 86, text: `se você quer alcançar (ex: sua meta de vendas do mês) preste atenção!`, category: 'autoridade' },
  { id: 87, text: `se você não está (ex: dominando o tráfego pago no TikTok), você está ficando para trás`, category: 'autoridade' },
  { id: 88, text: `se você é um(a) (ex: desenvolvedor de software júnior), você precisa ver isso.`, category: 'autoridade' },
  { id: 89, text: `aposto que você não sabia dessa (ex: dica de maquiagem para pele madura).`, category: 'autoridade' },
  { id: 90, text: `aposto que você não consegue fazer isso…`, category: 'autoridade' },
  { id: 91, text: `aposto que você não consegue adivinhar o que acontece a seguir…`, category: 'autoridade' },
  { id: 92, text: `Quando (ex: Viajantes experientes) Diz, “(ex: Sempre reserve seus voos com pelo menos 3 meses de antecedência para as melhores ofertas)”`, category: 'autoridade' },
  { id: 93, text: `(ex: Aprender a se comunicar abertamente com seu parceiro) Poderia Ser A Melhor Coisa Que Você Já Fez?`, category: 'curiosidade' },
  { id: 94, text: `E se Você Pudesse Trocar (ex: seu smartphone antigo) Por (ex: o novo drone com câmera 8K) – Você Faria Isso?`, category: 'curiosidade' },
  { id: 95, text: `Por que ninguém está falando sobre isso?`, category: 'revelacao' },
  { id: 96, text: `Note algo estranho sobre esta (ex: PINTURA ABSTRATA)?`, category: 'autoridade' },
  { id: 97, text: `Você consegue ver a diferença entre estas duas fotos?`, category: 'autoridade' },
  { id: 98, text: `Eu estou prestes a explodir sua mente…`, category: 'autoridade' },
  { id: 99, text: `Assista por sua conta e risco…`, category: 'autoridade' },
  { id: 100, text: `Continue assistindo apenas se você estiver bem com (ex: desafiar todas as suas crenças limitantes)…`, category: 'autoridade' },
  { id: 101, text: `Respostas honestas apenas: preciso da sua opinião.`, category: 'autoridade' },
  { id: 102, text: `Não acredito no que acabei de descobrir!`, category: 'autoridade' },
  { id: 103, text: `Não acredito como isso é simples.`, category: 'tutorial' },
  { id: 104, text: `Não acredito que não sabia disso sobre (investimentos em renda fixa para iniciantes).`, category: 'autoridade' },
  { id: 105, text: `Imagine alcançar (seu peso ideal em 3 meses) sem esforço.`, category: 'curiosidade' },
  { id: 106, text: `Imagine se você pudesse viajar pelo mundo sem sair do seu emprego.`, category: 'curiosidade' },
  { id: 107, text: `Imagine que você recebe um (smartphone que só funciona com Windows 95), não pode se livrar dele nem vendê-lo, o que você vai fazer com ele?`, category: 'curiosidade' },
  { id: 108, text: `Deixe-me contar uma breve história sobre (como uma campanha de e-mail marketing triplicou minhas vendas).`, category: 'historia' },
  { id: 109, text: `Deixe-me mostrar minha arma secreta!`, category: 'autoridade' },
  { id: 110, text: `Deixe-me contar sobre a vez em que...`, category: 'autoridade' },
  { id: 111, text: `Deixe-me apresentar algo rápido para vocês.`, category: 'urgencia' },
  { id: 112, text: `Fique atento para descobrir (o segredo para ter cabelo brilhante em apenas uma semana).`, category: 'autoridade' },
  { id: 113, text: `Fique atento — você não vai querer perder isso...`, category: 'autoridade' },
  { id: 114, text: `Pronto para um segredo que ninguém contou antes? Prepare-se para (melhorar a comunicação no seu casamento).`, category: 'revelacao' },
  { id: 115, text: `Pare de perder seu tempo com este erro!`, category: 'dor' },
  { id: 116, text: `É por isso que 60% das empresas falham após 3 anos.`, category: 'autoridade' },
  { id: 117, text: `A verdadeira história por trás de (a invenção do brigadeiro)...`, category: 'historia' },
  { id: 118, text: `A chocante verdade sobre (os bastidores das promoções de passagens aéreas).`, category: 'autoridade' },
  { id: 119, text: `O segredo para (fazer seu filho dormir a noite toda) é mais simples do que você pensa…`, category: 'revelacao' },
  { id: 120, text: `O segredo para dominar (a arte de escrever títulos irresistíveis).`, category: 'revelacao' },
  { id: 121, text: `O segredo para [resultado desejado] revelado.`, category: 'revelacao' },
  { id: 122, text: `O que você não sabe sobre o que realmente acontece em _____`, category: 'autoridade' },
  { id: 123, text: `O que você está prestes a ver é insano…`, category: 'autoridade' },
  { id: 124, text: `O que você está prestes a ver vai te surpreender…`, category: 'autoridade' },
  { id: 125, text: `O que está te impedindo de [objetivo]?`, category: 'autoridade' },
  { id: 126, text: `Por que o [objeto] atravessou a rua? Para [desfecho inesperado]!`, category: 'autoridade' },
  { id: 127, text: `Por que ninguém me contou isso antes?`, category: 'revelacao' },
  { id: 128, text: `Por que ninguém fala sobre isso?`, category: 'revelacao' },
  { id: 129, text: `Por que ninguém fala sobre os efeitos colaterais da meditação?`, category: 'revelacao' },
  { id: 130, text: `Por que ninguém está discutindo [relacionado ao nicho]?`, category: 'revelacao' },
  { id: 131, text: `Por que esperar? Comece sua jornada hoje!`, category: 'urgencia' },
  { id: 132, text: `Por que você deveria começar [ação específica] hoje.`, category: 'urgencia' },
  { id: 133, text: `Você não vai acreditar no que aconteceu depois…`, category: 'historia' },
  { id: 134, text: `Você não vai acreditar no que estou prestes a fazer…`, category: 'autoridade' },
  { id: 135, text: `Você não vai acreditar no que aconteceu quando eu [ação].`, category: 'historia' },
  { id: 136, text: `E se eu te dissesse [fato surpreendente]?`, category: 'curiosidade' },
  { id: 137, text: `E se eu te dissesse que existe uma maneira fácil de [alcançar o resultado desejado]?`, category: 'curiosidade' },
  { id: 138, text: `E se você pudesse mudar uma coisa sobre [tópico]?`, category: 'curiosidade' },
  { id: 139, text: `E se sua carreira dos sonhos estivesse a um passo de distância?`, category: 'curiosidade' },
  { id: 140, text: `O que aconteceria se ___?`, category: 'autoridade' },
  { id: 141, text: `O que acontece quando você mistura com [y]? Assista para descobrir…`, category: 'autoridade' },
  { id: 142, text: `Quer saber algo louco? Revele um fato inesperado.`, category: 'autoridade' },
  { id: 143, text: `Quer saber o segredo para [resultado desejado]? Assista até o final...`, category: 'revelacao' },
  { id: 144, text: `Quer aprender como [alcançar algo]? Assista a isto…`, category: 'tutorial' },
  { id: 145, text: `O que acontece a seguir vai te surpreender.`, category: 'autoridade' },
  { id: 146, text: `O que você faria se [uma situação específica] ocorresse?`, category: 'autoridade' },
  { id: 147, text: `O que você faria se pudesse mudar de carreira hoje?`, category: 'urgencia' },
  { id: 148, text: `Você nunca deveria [AÇÃO COMPLETA] quando você...`, category: 'autoridade' },
  { id: 149, text: `Você sempre deveria...`, category: 'autoridade' },
  { id: 150, text: `Estou prestes a expor....`, category: 'revelacao' },
  { id: 151, text: `O maior sinal de alerta...`, category: 'autoridade' },
  { id: 152, text: `Eu não ia compartilhar isso, mas _____`, category: 'autoridade' },
  { id: 153, text: `Estou prestes a desmascarar o maior mito em _____`, category: 'autoridade' },
  { id: 154, text: `Você pode deixar de me seguir por eu dizer isso, mas _____`, category: 'curiosidade' },
  { id: 155, text: `Por que ______ ainda é uma coisa em 202*?`, category: 'autoridade' },
  { id: 156, text: `Se você fizer ___________, vou te denunciar.`, category: 'autoridade' },
  { id: 157, text: `Por que ninguém está falando sobre dicas de ___?`, category: 'revelacao' },
  { id: 158, text: `O ___ Perfeito Não Existe`, category: 'autoridade' },
  { id: 159, text: `Este é um mito pouco conhecido, mas muito prejudicial na indústria de ___`, category: 'autoridade' },
  { id: 160, text: `Se você ainda não experimentou ___, assista a isso!`, category: 'autoridade' },
  { id: 161, text: `Por que ninguém está falando sobre isso ___`, category: 'revelacao' },
  { id: 162, text: `Imagine se você pudesse ___`, category: 'curiosidade' },
  { id: 163, text: `Tudo o que você sabe sobre ___ está ERRADO!`, category: 'autoridade' },
  { id: 164, text: `Qual seria sua reação se descobrisse o segredo para a saúde perfeita?`, category: 'revelacao' },
  { id: 165, text: `Isso não é uma piada: continue com uma declaração séria ou surpreendente.`, category: 'autoridade' },
  { id: 166, text: `Isso é tão inacreditável, mas é verdade…`, category: 'autoridade' },
  { id: 167, text: `Esta é a coisa mais legal que você verá hoje…`, category: 'urgencia' },
  { id: 168, text: `Esta é a coisa mais maluca que eu já vi…`, category: 'autoridade' },
  { id: 169, text: `Esta é a maneira mais acessível de [alcançar algo].`, category: 'autoridade' },
  { id: 170, text: `Este é o método mais confiável para [tarefa].`, category: 'tutorial' },
  { id: 171, text: `Esta é a solução definitiva para ___.`, category: 'autoridade' },
  { id: 172, text: `É isso que [pessoa famosa] esconde sobre o que ensina…`, category: 'autoridade' },
  { id: 173, text: `É por isso que [tática para público-alvo] não está funcionando.`, category: 'dor' },
  { id: 174, text: `Se você é novo no Tik Tok, tenho uma pergunta para você…`, category: 'autoridade' },
  { id: 175, text: `Estou prestes a te contar o SEGREDO MAIS guardado em [INDUSTRIA, TEMA]…`, category: 'revelacao' },
  { id: 176, text: `Aqui está algo que [PESSOA OU GRUPO DE PESSOAS] não quer que você saiba:`, category: 'autoridade' },
  { id: 177, text: `Aqui está um hack (de plataforma social / relacionado a nicho / tópico da indústria) maluco que você não está pronto para ouvir, mas... é honestamente a verdade.`, category: 'autoridade' },
  { id: 178, text: `Este [ITEM] vai mudar sua vida...`, category: 'autoridade' },
  { id: 179, text: `ISTO é o que está impedindo você de [CONQUISTA]`, category: 'autoridade' },
  { id: 180, text: `A coisa mais prejudicial para [OBJETO, MENTALIDADE, META, ETC.] é...`, category: 'autoridade' },
  { id: 181, text: `Este fato está prestes a mudar sua vida...`, category: 'autoridade' },
  { id: 182, text: `A pior coisa que você pode [FAZER, PENSAR, DIZER] [ANTES/DEPOIS DO EVENTO]`, category: 'autoridade' },
  { id: 183, text: `Este (site / ferramenta / aplicativo) ajudou centenas de milhares de (título de cargo relacionado a nicho) a impulsionar seu conteúdo literalmente da noite para o dia!`, category: 'autoridade' },
  { id: 184, text: `Você Não Vai Acreditar no Que Isso É...`, category: 'autoridade' },
  { id: 185, text: `Novo código secreto do X`, category: 'autoridade' },
  { id: 186, text: `*"[Público-alvo], preciso da sua ajuda! Vamos trabalhar juntos para [alcançar objetivo comum]."*`, category: 'autoridade' },
  { id: 187, text: `*"Você experimentaria esta inovadora [estratégia/ferramenta] para si mesmo e veria os resultados incríveis que ela pode trazer?"*`, category: 'dor' },
  { id: 188, text: `*"Sentindo-se sobrecarregado com seu [desafio específico]? Aqui está a solução que você estava procurando."*`, category: 'autoridade' },
  { id: 189, text: `*"Por que ninguém está falando sobre esta [estratégia/produto] que muda o jogo? Vamos mergulhar e mudar o jogo."*`, category: 'revelacao' },
  { id: 190, text: `*"Cansado de tentar [métodos ineficazes] que simplesmente não funcionam? Deixe-me mostrar o que funciona."*`, category: 'dor' },
  { id: 191, text: `Por que ninguém fala sobre isso?`, category: 'revelacao' },
  { id: 192, text: `Este único erro pode estar lhe custando (\\\\$)`, category: 'dor' },
  { id: 193, text: `Expondo meu segredo para (em branco)`, category: 'revelacao' },
  { id: 194, text: `Tudo o que você sabia sobre (assunto) está ERRADO!`, category: 'curiosidade' },
  { id: 195, text: `Isso vai mudar a forma como você usa (em branco)`, category: 'tutorial' },
  { id: 196, text: `É só comigo, ou…`, category: 'autoridade' },
  { id: 197, text: `Imagine se você pudesse (inserir resultado aqui)`, category: 'curiosidade' },
  { id: 198, text: `É por isso que sua (ação) não está funcionando`, category: 'dor' },
  { id: 199, text: `Aqui está minha rotina de exercícios que eu gostaria de ter conhecido no ensino médio`, category: 'autoridade' },
  { id: 200, text: `Meu maior arrependimento é não ter tentado isto ______ mais cedo`, category: 'dor' },
  { id: 201, text: `Este é um sinal para…`, category: 'autoridade' },
  { id: 202, text: `*"Se você tem [problema específico], preste atenção nesta [solução]."*`, category: 'autoridade' },
  { id: 203, text: `*"Pare de rolar se você tem [ponto de dor], experimente esta [solução única]."*`, category: 'dor' },
  { id: 204, text: `*"Veja por que seu [processo/estratégia] não está funcionando – e como consertá-lo de vez."*`, category: 'dor' },
  { id: 205, text: `*"Ninguém está falando sobre este [produto/estratégia inovadora] na [comunidade/indústria específica]."*`, category: 'dor' },
  { id: 206, text: `*"Você não vai acreditar neste [adjetivo] [truque/dica] que mudará tudo para seu [público/objetivo]."*`, category: 'autoridade' },
  { id: 207, text: `Não acredito que este [produto/serviço] custa apenas \\\\$[preço].`, category: 'autoridade' },
  { id: 208, text: `Você não vai acreditar nesta coisa chamada "[conceito]".`, category: 'autoridade' },
  { id: 209, text: `Algo que você não sabia sobre [tópico].`, category: 'autoridade' },
  { id: 210, text: `O segredo mais bem guardado para [alcançar algo].`, category: 'revelacao' },
  { id: 211, text: `Não consigo superar este [produto/serviço]!`, category: 'autoridade' },
  { id: 212, text: `Assista a isto se você odeia [desafio específico].`, category: 'autoridade' },
  { id: 213, text: `Este é o dia [X] do meu desafio de [X] dias.`, category: 'autoridade' },
  { id: 214, text: `Se você tem problemas com [questão específica da sua indústria], preste atenção.`, category: 'autoridade' },
  { id: 215, text: `Pare de rolar se você está cansado de [problema específico da indústria].`, category: 'dor' },
  { id: 216, text: `Por que ninguém está falando sobre este [tópico relacionado à indústria]?`, category: 'revelacao' },
  { id: 217, text: `Você não vai acreditar nesta coisa chamada "[termo específico da indústria]".`, category: 'autoridade' },
  { id: 218, text: `Algo que você não sabia sobre [tópico específico da indústria].`, category: 'autoridade' },
  { id: 219, text: `Se você está cético sobre [aspecto específico da indústria], assista a isto.`, category: 'autoridade' },
  { id: 220, text: `Assista a isto se você odeia [desafio específico da indústria].`, category: 'autoridade' },
  { id: 221, text: `Aviso para [público-alvo], isto é um divisor de águas.`, category: 'autoridade' },
  { id: 222, text: `O [indústria/produto] perfeito não existe, mas esta é a maneira de ser o melhor que você pode ser.`, category: 'curiosidade' },
  { id: 223, text: `Você não vai acreditar no que acontece quando você [ação].`, category: 'autoridade' },
  { id: 224, text: `Esta técnica simples pode mudar seu [resultado específico] da noite para o dia.`, category: 'autoridade' },
  { id: 225, text: `Este é o segredo para dominar [tópico] sem esforço.`, category: 'revelacao' },
  { id: 226, text: `Se você não está fazendo [ação], está perdendo [resultado].`, category: 'dor' },
  { id: 227, text: `Especialistas em [indústria] não estão te contando isto.`, category: 'autoridade' },
  { id: 228, text: `A única coisa que mudou tudo sobre como eu [resultado].`, category: 'tutorial' },
  { id: 229, text: `O que todo mundo está entendendo errado sobre [tópico].`, category: 'autoridade' },
  { id: 230, text: `Por que ninguém está falando sobre [segredo/estratégia]?`, category: 'revelacao' },
  { id: 231, text: `"Você precisa agir rápido para ver resultados!"`, category: 'urgencia' },
  { id: 232, text: `"Não perca esta oferta por tempo limitado!"`, category: 'urgencia' },
  { id: 233, text: `"Isto só estará disponível por um curto período!"`, category: 'autoridade' },
  { id: 234, text: `"Se você quer melhorar, comece hoje!"`, category: 'urgencia' },
  { id: 235, text: `"Sua chance de mudar de vida é agora!"`, category: 'urgencia' },
  { id: 236, text: `"Por que esperar? Comece sua jornada hoje!"`, category: 'urgencia' },
  { id: 237, text: `"Você merece saber disto — não espere!"`, category: 'autoridade' },
  { id: 238, text: `"O momento de fazer uma mudança é agora!"`, category: 'urgencia' },
  { id: 239, text: `"Este pode ser seu ponto de virada — não o ignore!"`, category: 'curiosidade' },
  { id: 240, text: `"Dê o primeiro passo rumo a [objetivo] hoje!"`, category: 'urgencia' },
  { id: 241, text: `Descubra o segredo para [resultado desejado].`, category: 'revelacao' },
  { id: 242, text: `Quer dobrar seus resultados em [área específica]? Assista a isto!`, category: 'autoridade' },
  { id: 243, text: `Atenção [público-alvo]: Prepare-se para um vídeo alucinante!`, category: 'autoridade' },
  { id: 244, text: `Descubra os benefícios ocultos de [produto/serviço].`, category: 'autoridade' },
  { id: 245, text: `Quer saber as dicas exclusivas para [resultado desejado]? Assista agora!`, category: 'urgencia' },
  { id: 246, text: `Quer alcançar [resultado desejado]? Deixe-me te mostrar como.`, category: 'tutorial' },
  { id: 247, text: `Quer saber a história não contada por trás de [produto/serviço]? Assista agora!`, category: 'historia' },
  { id: 248, text: `Descubra o potencial inexplorado de [resolver um problema] neste vídeo.`, category: 'autoridade' },
  { id: 249, text: `Você não vai acreditar nisto, mas ____`, category: 'autoridade' },
  { id: 250, text: `Quais são algumas coisas estranhas que as pessoas não sabem sobre _____`, category: 'autoridade' },
  { id: 251, text: `Eu acho que as pessoas não entendem ____.`, category: 'autoridade' },
  { id: 252, text: `Eu sou o único que não sabia ____.`, category: 'autoridade' },
  { id: 253, text: `Todo mundo está procurando por ____.`, category: 'autoridade' },
  { id: 254, text: `Se você quer ____ faça isso.`, category: 'autoridade' },
  { id: 255, text: `Este é o seu sinal para ___.`, category: 'autoridade' },
  { id: 256, text: `Por que ninguém está falando sobre ___.`, category: 'revelacao' },
  { id: 257, text: `Você sabia que ___ não ___ como você pensa?`, category: 'curiosidade' },
  { id: 258, text: `5 Maneiras que eu fiz ____, e a 4ª é a melhor…`, category: 'lista' },
  { id: 259, text: `3 Razões pelas quais eu amo ___`, category: 'lista' },
  { id: 260, text: `5 Razões pelas quais eu uso ___…`, category: 'lista' },
  { id: 261, text: `Aqui estão 3 maneiras rápidas de obter ___`, category: 'lista' },
  { id: 262, text: `___ Razão pela qual você deveria estar usando ___`, category: 'autoridade' },
  { id: 263, text: `3 Maneiras de fazer ___…`, category: 'lista' },
  { id: 264, text: `aqui está como alcançar [resultado positivo] em apenas [número] passos fáceis!`, category: 'tutorial' },
  { id: 265, text: `perguntei a [número] especialistas sobre [tópico], e aqui está o que eles disseram.`, category: 'autoridade' },
  { id: 266, text: `auditei [número] websites. aqui estão [número] dicas para aumentar as conversões...`, category: 'autoridade' },
  { id: 267, text: `segui [rotina] e superou minhas expectativas.`, category: 'autoridade' },
  { id: 268, text: `aqui está como aproveitar ao máximo seu [tempo ou recursos] em apenas [curto período de tempo].`, category: 'experiencia' },
  { id: 269, text: `5 Coisas que eu gostaria de saber antes de eu ___`, category: 'lista' },
  { id: 270, text: `Aqui estão 3 sinais de que você deveria ___`, category: 'autoridade' },
  { id: 271, text: `3 ___ mudaram minha vida`, category: 'lista' },
  { id: 272, text: `5 Dicas para se livrar de ___`, category: 'lista' },
  { id: 273, text: `vamos analisar isso passo a passo.`, category: 'tutorial' },
  { id: 274, text: `vamos falar sobre as # coisas que vão te salvar de x.`, category: 'autoridade' },
  { id: 275, text: `vamos descobrir por que [problema] persiste e como superá-lo.`, category: 'tutorial' },
  { id: 276, text: `let’s ver se isso actually funciona!`, category: 'autoridade' },
  { id: 277, text: `let’s talk sobre o mistakes eu made quando [situação ou activity].`, category: 'dor' },
  { id: 278, text: `let’s talk sobre por que [popular opinion] é misguided…`, category: 'autoridade' },
  { id: 279, text: `vida truque alert! did você saber…`, category: 'autoridade' },
  { id: 280, text: `mistakes eu made quando (público-alvo)`, category: 'dor' },
  { id: 281, text: `razões por que você should x.`, category: 'autoridade' },
  { id: 282, text: `red flags para olhar para em ___.`, category: 'autoridade' },
  { id: 283, text: `eu’m going para tentar 5 most popular [relacionado ao nicho]`, category: 'autoridade' },
  { id: 284, text: `eu’ve apenas tentou 5 [relacionado ao nicho] você pode ter apenas em xxx`, category: 'autoridade' },
  { id: 285, text: `se você’re like me, você need para tente isso.`, category: 'autoridade' },
  { id: 286, text: `3 coisas você probably não saber sobre [trabalho, ferramenta, EVENTO, ETC]...`, category: 'lista' },
  { id: 287, text: `3 signs você should {insira algo que seu audiência should começar doing}`, category: 'lista' },
  { id: 288, text: `Aqui são o 3 razões por que {insira um dor}`, category: 'lista' },
  { id: 289, text: `5-Minuto (tópico) para Become (desirable resultado)`, category: 'autoridade' },
  { id: 290, text: `[número] jeitos para fazer ___ …`, category: 'autoridade' },
  { id: 291, text: `[número] coisas que eu queria ter sabido antes Eu ___`, category: 'autoridade' },
  { id: 292, text: `[número] coisas que sentir Illegal para saber`, category: 'curiosidade' },
  { id: 293, text: `[número] razões Por que seu (negócio) é (undesirable resultado)`, category: 'curiosidade' },
  { id: 295, text: `[número] Achievements Isso Client tinha During (program)`, category: 'autoridade' },
  { id: 296, text: `[número] eye-opening insights eu gained este ano que rocked meu mundo em [área específica]`, category: 'autoridade' },
  { id: 297, text: `[número] hacks para supercharge seu [área específica] game!`, category: 'curiosidade' },
  { id: 298, text: `[número] passos para achieve [resultado] que brings [benefit]`, category: 'autoridade' },
  { id: 299, text: `eu read 50 books em personal development; these são o key takeaways.`, category: 'autoridade' },
  { id: 300, text: `eu tested [truque/dica/trick], então você don’t ter para ___.`, category: 'autoridade' },
  { id: 301, text: `eu tested [method], e aqui's o que eu encontrei.`, category: 'autoridade' },
  { id: 302, text: `Eu testei [produto/serviço], e aqui está minha análise.`, category: 'experiencia' },
  { id: 303, text: `Eu testei [tendência viral], e os resultados chegaram.`, category: 'experiencia' },
  { id: 304, text: `Eu experimentei [método/produto], e aqui está o que aprendi.`, category: 'experiencia' },
  { id: 305, text: `Eu experimentei [método] por [período de tempo], e aqui está o que aconteceu.`, category: 'historia' },
  { id: 306, text: `Eu experimentei tudo e este é o melhor.`, category: 'experiencia' },
  { id: 307, text: `Eu experimentei todos os ______ que existem e aqui estão os resultados.`, category: 'experiencia' },
  { id: 308, text: `Eu experimentei todos os aplicativos de produtividade, e aqui está o que funcionou.`, category: 'experiencia' },
  { id: 309, text: `[número] passos para dominar [habilidade] que levarão a [benefício].`, category: 'autoridade' },
  { id: 310, text: `[número] fatos surpreendentes sobre [tópico] que vão [resultado].`, category: 'autoridade' },
  { id: 311, text: `[número] maneiras de alcançar [resultado]!`, category: 'autoridade' },
  { id: 312, text: `[número] maneiras de melhorar seu desempenho em [área específica]!`, category: 'autoridade' },
  { id: 313, text: `8 ferramentas [relacionadas ao nicho] que economizarão centenas de horas de trabalho.`, category: 'lista' },
  { id: 314, text: `10 dicas para melhorar sua [habilidade] imediatamente.`, category: 'lista' },
  { id: 315, text: `7 segredos para [algo importante].`, category: 'lista' },
  { id: 316, text: `40 coisas que eu gostaria de ter sabido há 10 anos.`, category: 'lista' },
  { id: 317, text: `5 erros que você deve evitar se quiser ter sucesso em fotografia.`, category: 'lista' },
  { id: 318, text: `5 coisas que você pode fazer agora mesmo para melhorar ___.`, category: 'lista' },
  { id: 319, text: `8 canais do YouTube nos quais você aprenderá mais do que em 4 anos de faculdade.`, category: 'lista' },
  { id: 320, text: `Aqui estão [número] truques subestimados para [resultado desejado]...`, category: 'autoridade' },
  { id: 321, text: `Aqui está uma fórmula de [número] passos para [alcançar resultado] mais rápido...`, category: 'urgencia' },
  { id: 322, text: `Aqui está uma série de [número] partes sobre [tópico].`, category: 'autoridade' },
  { id: 323, text: `Aqui está uma lista de verificação de [número] passos para [tarefa].`, category: 'autoridade' },
  { id: 324, text: `Aqui está um processo de [número] passos para [alcançar resultado].`, category: 'autoridade' },
  { id: 325, text: `(Número) Coisas Que Te Impedirão De (Resultado).`, category: 'autoridade' },
  { id: 326, text: `(Número) Dicas Para Ser Mais (Resultado Desejado).`, category: 'autoridade' },
  { id: 327, text: `Os (Número) Traços Que Te Tornam (Resultado Desejado)`, category: 'autoridade' },
  { id: 328, text: `(Número) Técnicas Para Se Tornar (Resultado Desejado)`, category: 'autoridade' },
  { id: 329, text: `3 coisas que você provavelmente não sabe sobre [EMPREGO, FERRAMENTA, EVENTO, ETC]...`, category: 'lista' },
  { id: 330, text: `Aqui está um tutorial de [número] minutos sobre [habilidade].`, category: 'tutorial' },
  { id: 331, text: `Aqui está um resumo de [número] minutos sobre [tópico].`, category: 'autoridade' },
  { id: 332, text: `Aqui está um treino de [número] minutos para [objetivo específico].`, category: 'autoridade' },
  { id: 333, text: `Aqui está uma estratégia de [número] minutos para [objetivo].`, category: 'autoridade' },
  { id: 334, text: `O melhor [produto/serviço] para [necessidade específica]...`, category: 'autoridade' },
  { id: 335, text: `As melhores alternativas de [produto] para [problema].`, category: 'autoridade' },
  { id: 336, text: `O melhor [produto] para [público específico].`, category: 'autoridade' },
  { id: 337, text: `O melhor que você deveria experimentar hoje…`, category: 'urgencia' },
  { id: 338, text: `O melhor conselho que já recebi sobre [tópico]...`, category: 'autoridade' },
  { id: 339, text: `A melhor maneira de [realizar uma tarefa] sem [obstáculo comum].`, category: 'autoridade' },
  { id: 340, text: `O segredo mais bem guardado para [alcançar um objetivo].`, category: 'revelacao' },
  { id: 341, text: `O [app/ferramenta] mais subestimado que você precisa experimentar.`, category: 'autoridade' },
  { id: 342, text: `X mitos que criadores de [nicho] erram completamente…`, category: 'dor' },
  { id: 343, text: `3 Razões Pelas Quais Eu Amo ___`, category: 'lista' },
  { id: 344, text: `5 Maneiras Que Eu Fiz ___, E A 4ª É A Melhor …`, category: 'lista' },
  { id: 345, text: `Coisas Que Eu Gostaria de Saber Mais Cedo Parte ___`, category: 'autoridade' },
  { id: 346, text: `5 Dicas Para Se Livrar de ___`, category: 'lista' },
  { id: 347, text: `5 Razões Pelas Quais Eu Uso ___…`, category: 'lista' },
  { id: 348, text: `5 Coisas Que Eu Gostaria de Saber Antes de ___`, category: 'lista' },
  { id: 349, text: `Estes 3 ___ mudaram minha vida`, category: 'autoridade' },
  { id: 350, text: `3 Maneiras de Fazer ___ …`, category: 'lista' },
  { id: 351, text: `___ coisas que parecem ilegais de saber`, category: 'autoridade' },
  { id: 352, text: `Aqui estão 3 maneiras rápidas de obter ___`, category: 'lista' },
  { id: 353, text: `X coisas que eu gostaria de ter sabido antes, mas não soube, então estou compartilhando com você.`, category: 'autoridade' },
  { id: 354, text: `X% do [público-alvo] está [enfrentando um problema específico], e eis o porquê.`, category: 'autoridade' },
  { id: 355, text: `X imagens que vão te tornar um [especialista] melhor...`, category: 'autoridade' },
  { id: 356, text: `X passos para (resultado desejado)`, category: 'autoridade' },
  { id: 357, text: `Você precisa dessas [ferramentas ou recursos] para facilitar a vida!`, category: 'autoridade' },
  { id: 358, text: `Você precisa desta ferramenta gratuita para ___`, category: 'autoridade' },
  { id: 359, text: `Você precisa disso se quiser ______`, category: 'autoridade' },
  { id: 360, text: `Você precisa deste produto na sua vida!`, category: 'autoridade' },
  { id: 361, text: `Principais [número] razões pelas quais [declaração].`, category: 'autoridade' },
  { id: 362, text: `3 principais coisas que você precisa saber sobre ___...`, category: 'lista' },
  { id: 363, text: `[NÚMERO] [ITENS] que estou amando para [ALCANÇAR ALGO]...`, category: 'autoridade' },
  { id: 364, text: `5 produtos de farmácia que estou amando para looks de maquiagem natural...`, category: 'lista' },
  { id: 365, text: `Estes [NÚMERO] [ITENS] vão mudar a maneira como você [ALCANÇA ALGO]...`, category: 'tutorial' },
  { id: 366, text: `5 melhores coisas para fazer em (local) que seu espectador deseja / quer...`, category: 'lista' },
  { id: 367, text: `Aqui estão 3 coisas que você PRECISA estar usando se você é um (nicho/título/relacionamento).`, category: 'lista' },
  { id: 368, text: `Aqui estão meus 3 principais truques de [cargo / setor / nicho / título profissional]!`, category: 'autoridade' },
  { id: 369, text: `(Número) (produto) incrivelmente úteis que estão prestes a mudar sua vida!`, category: 'autoridade' },
  { id: 370, text: `Aqui estão meus 3 principais truques de [cargo / setor / nicho / título profissional]!`, category: 'autoridade' },
  { id: 371, text: `Sites de (nicho / setor / plataforma) que você TEM que marcar! Parte (número alto).`, category: 'autoridade' },
  { id: 372, text: `Aqui está a coisa nº 1 que você deve pensar ao comprar (assunto / objeto / serviço relacionado ao seu nicho).`, category: 'autoridade' },
  { id: 373, text: `3 principais maneiras de [alcançar um objetivo]…`, category: 'lista' },
  { id: 374, text: `5 principais razões pelas quais [algo acontece].`, category: 'lista' },
  { id: 375, text: `5 principais ferramentas para [tarefa específica]…`, category: 'lista' },
  { id: 376, text: `Principais truques para [resolver um problema].`, category: 'autoridade' },
  { id: 377, text: `Esta é a minha dica nº 1 para [nicho].`, category: 'autoridade' },
  { id: 379, text: `Esta é a melhor maneira de [resolver problema] em 2024.`, category: 'autoridade' },
  { id: 380, text: `Esta é a melhor maneira de lidar com ___.`, category: 'autoridade' },
  { id: 381, text: `Esta é a diferença entre [relacionado ao nicho] de luxo e [relacionado ao nicho] de massa.`, category: 'autoridade' },
  { id: 382, text: `Esta é a chave para [resultado desejado].`, category: 'autoridade' },
  { id: 383, text: `Este é o método mais direto para [tarefa].`, category: 'tutorial' },
  { id: 384, text: `Esta é a maneira mais rápida de [alcançar objetivo].`, category: 'autoridade' },
  { id: 385, text: `Esta é a maneira mais simples de [alcançar objetivo].`, category: 'autoridade' },
  { id: 386, text: `Esta é a maneira mais simples de obter um [resultado desejado] e ajudar [fazer algo bom].`, category: 'autoridade' },
  { id: 387, text: `Este é o hack definitivo para [resultado desejado].`, category: 'autoridade' },
  { id: 388, text: `5 Razões pelas quais eu uso..(x)`, category: 'lista' },
  { id: 389, text: `5 Dicas para se livrar de (x)`, category: 'lista' },
  { id: 390, text: `5 Coisas que eu gostaria de saber antes de (tentar todas essas outras soluções x)`, category: 'lista' },
  { id: 391, text: `Aqui está (quantidade) (hack/dica/truque) subestimado`, category: 'autoridade' },
  { id: 392, text: `Estes 3 livros mudaram minha vida`, category: 'autoridade' },
  { id: 394, text: `Aqui estão 3 maneiras rápidas de obter (solução)`, category: 'lista' },
  { id: 395, text: `Aqui estão 3 sinais de que você deveria (ação)`, category: 'autoridade' },
  { id: 396, text: `Principais 3 erros que você está cometendo em/fazendo X`, category: 'lista' },
  { id: 397, text: `*"Aqui estão [número] [estratégias/dicas/produtos] para resolver [problema/alcançar objetivo]."*`, category: 'autoridade' },
  { id: 398, text: `*"[Número] coisas que todo [público-alvo] precisa [alcançar resultado desejado]."*`, category: 'autoridade' },
  { id: 399, text: `*"Você está cometendo estes [número] erros comuns em [processo específico]? Evite-os para [alcançar resultado]."*`, category: 'dor' },
  { id: 400, text: `*"[Número] [ferramentas/dicas] subestimadas para [resultado específico]."*`, category: 'autoridade' },
  { id: 401, text: `"Estes [número] [itens/hábitos] vão mudar`, category: 'autoridade' },
  { id: 402, text: `10 coisas que você não está fazendo para [alcançar objetivo].`, category: 'lista' },
  { id: 403, text: `7 coisas que você não está fazendo para [objetivo].`, category: 'lista' },
  { id: 404, text: `5 coisas que você não está fazendo para [melhorar área específica].`, category: 'lista' },
  { id: 405, text: `3 dicas para te ajudar a [resolver um problema].`, category: 'lista' },
  { id: 406, text: `5 coisas que você não está fazendo para [demonstrar amor/apreço].`, category: 'lista' },
  { id: 407, text: `3 dicas para te ajudar a [superar a ansiedade].`, category: 'lista' },
  { id: 408, text: `5 coisas que você não está fazendo para [obter melhores resultados].`, category: 'lista' },
  { id: 409, text: `[Número] coisas que todo(a) [público-alvo da indústria] precisa para [alcançar objetivo].`, category: 'autoridade' },
  { id: 410, text: `5 coisas que você não está fazendo para [alcançar resultado específico na sua indústria].`, category: 'lista' },
  { id: 411, text: `10 coisas que você não está fazendo para melhorar sua [habilidade ou resultado específico da indústria].`, category: 'lista' },
  { id: 412, text: `[Número] dicas para te ajudar a [resolver problema específico da indústria].`, category: 'autoridade' },
  { id: 413, text: `[Número] coisas que você deveria saber sobre [tópico relacionado à indústria].`, category: 'autoridade' },
  { id: 414, text: `10 coisas que você não está fazendo para [resultado desejado].`, category: 'lista' },
  { id: 415, text: `5 maneiras simples de melhorar sua [habilidade/área da vida].`, category: 'lista' },
  { id: 416, text: `7 erros comuns que as pessoas cometem ao [atividade].`, category: 'lista' },
  { id: 417, text: `3 coisas que você precisa começar a fazer hoje para [resultado].`, category: 'lista' },
  { id: 418, text: `6 coisas que todo(a) especialista em [indústria] precisa saber.`, category: 'lista' },
  { id: 419, text: `As principais [X] dicas para [alcançar resultado específico].`, category: 'autoridade' },
  { id: 420, text: `maneiras de resolver [problema] mais rápido do que nunca.`, category: 'urgencia' },
  { id: 421, text: `5 segredos da [indústria] que você precisa saber.`, category: 'lista' },
  { id: 422, text: `10 dicas que você pode seguir para [resultado desejado].`, category: 'lista' },
  { id: 423, text: `6 coisas que todo investidor de criptomoedas precisa saber.`, category: 'lista' },
  { id: 424, text: `10 coisas que você não está fazendo para apoiar o desenvolvimento do seu filho.`, category: 'lista' },
  { id: 425, text: `5 maneiras simples de melhorar sua clareza mental.`, category: 'lista' },
  { id: 426, text: `10 coisas que você não está fazendo para maximizar seus lucros em criptomoedas.`, category: 'lista' },
  { id: 427, text: `3 dicas para te ajudar a tirar melhores fotos de retratos.`, category: 'lista' },
  { id: 428, text: `___ Razões Pelas Quais ___`, category: 'autoridade' },
  { id: 429, text: `10 (ferramentas ou dicas) que eu gostaria de saber mais cedo.`, category: 'lista' },
  { id: 430, text: `___ motivos para fazer ___.`, category: 'autoridade' },
  { id: 431, text: `Em 60 segundos, vou te mostrar ___.`, category: 'autoridade' },
  { id: 432, text: `Os ___ segredos para ____.`, category: 'revelacao' },
  { id: 433, text: `Por que você luta para ___, Aqui estão (Insira o número) Dicas`, category: 'autoridade' },
  { id: 434, text: `"Aqui estão 5 coisas que eu gostaria de saber antes de [tópico]..."`, category: 'lista' },
  { id: 435, text: `"Estes 7 hábitos estão mudando o jogo para [nicho] – e você deveria começar HOJE!"`, category: 'lista' },
  { id: 436, text: `"Quer crescer mais rápido? Aqui estão 10 estratégias comprovadas para [objetivo]..."`, category: 'urgencia' },
  { id: 437, text: `"As 3 dicas essenciais para [público] para [alcançar resultado]..."`, category: 'lista' },
  { id: 438, text: `"Eu tentei estas 4 coisas por 30 dias e eis o que aconteceu..."`, category: 'lista' },
  { id: 439, text: `"Não cometa estes 6 erros se você quer [alcançar resultado]..."`, category: 'lista' },
  { id: 440, text: `"Aqui está uma lista simples de 10 maneiras de impulsionar sua [habilidade/negócio]"`, category: 'lista' },
  { id: 441, text: `"Segui estes 5 passos para o sucesso e funcionou – eis como!"`, category: 'lista' },
  { id: 442, text: `"Você tem feito [coisa] errado por anos! Aqui estão 3 correções simples..."`, category: 'autoridade' },
  { id: 443, text: `"Estas 8 estratégias poderosas te ajudarão a [alcançar objetivo] rapidamente!"`, category: 'autoridade' },
  { id: 444, text: `"As 5 coisas que parei de fazer para crescer meu [público/negócio]..."`, category: 'lista' },
  { id: 445, text: `"Quer mais engajamento? Estas 4 dicas vão explodir seu alcance..."`, category: 'lista' },
  { id: 446, text: `"Aqui estão as 10 melhores ferramentas que eu uso para [alcançar objetivo]..."`, category: 'autoridade' },
  { id: 447, text: `"Se sentindo travado? Experimente estes 6 truques para começar a ver resultados reais..."`, category: 'lista' },
  { id: 448, text: `"Acha que sabe tudo? Aqui estão 7 dicas negligenciadas para o sucesso em [nicho]..."`, category: 'lista' },
  { id: 449, text: `"Estas 5 funcionalidades do Instagram vão mudar para sempre a forma como você [faz marketing/interage]!"`, category: 'tutorial' },
  { id: 450, text: `"Quer se destacar? Aqui estão 4 maneiras únicas de [obter resultados]..."`, category: 'lista' },
  { id: 451, text: `"Este simples processo de 3 passos pode te ajudar a [objetivo] em tempo recorde!"`, category: 'lista' },
  { id: 452, text: `"Não perca: 6 coisas que você precisa parar de fazer AGORA MESMO para [alcançar objetivo]..."`, category: 'lista' },
  { id: 453, text: `"Estes 9 truques surpreendentes te ajudarão a obter [resultado desejado] – garantido!"`, category: 'lista' },
  { id: 454, text: `5 segredos para [resultado desejado]!`, category: 'lista' },
  { id: 455, text: `Quer [resultado]? Comece com estes 3 passos!`, category: 'lista' },
  { id: 456, text: `A única coisa que você precisa parar de fazer hoje...`, category: 'urgencia' },
  { id: 457, text: `Com dificuldades em [problema]? Aqui está a solução!`, category: 'autoridade' },
  { id: 458, text: `Esta fórmula de 4 passos vai mudar seu [resultado]...`, category: 'lista' },
  { id: 459, text: `Pare de perder tempo! Faça isso em vez disso...`, category: 'autoridade' },
  { id: 460, text: `Quer viralizar? Experimente estas 5 táticas!`, category: 'autoridade' },
  { id: 461, text: `A melhor dica para [público] arrasar em [objetivo]!`, category: 'autoridade' },
  { id: 462, text: `Desbloqueie seu potencial com estas 3 dicas simples!`, category: 'lista' },
  { id: 463, text: `Estas 2 estratégias vão transformar seu [negócio/marca]!`, category: 'autoridade' },
  { id: 464, text: `Conseguindo meu ___ diário diferente com…`, category: 'autoridade' },
  { id: 465, text: `Como eu faço ___!`, category: 'tutorial' },
  { id: 466, text: `Ok, estou compartilhando meu segredo de como eu ___`, category: 'revelacao' },
  { id: 467, text: `Imagine se você pudesse ___`, category: 'curiosidade' },
  { id: 468, text: `Semana passada eu estava fazendo ___ quando ___ aconteceu…`, category: 'historia' },
  { id: 469, text: `Veja o que (Cliente) disse sobre o (programa) depois de (período de tempo)`, category: 'autoridade' },
  { id: 470, text: `De (ponto A) a (ponto B) Veja o que (nome) conquistou em (período de tempo)`, category: 'autoridade' },
  { id: 471, text: `A Maneira #1 de Fazer ___…`, category: 'autoridade' },
  { id: 472, text: `tudo começou quando decidi [fazer algo ousado]…`, category: 'autoridade' },
  { id: 473, text: `era uma vez, eu enfrentei [desafio]…`, category: 'historia' },
  { id: 474, text: `algo incrível aconteceu, e aqui está o que...`, category: 'historia' },
  { id: 475, text: `algo incrível está prestes a acontecer…`, category: 'autoridade' },
  { id: 476, text: `deixe-me contar uma pequena história sobre [evento].`, category: 'historia' },
  { id: 477, text: `deixe-me mostrar minha arma secreta!`, category: 'autoridade' },
  { id: 478, text: `deixe-me contar sobre a vez em que [experimentei algo único]…`, category: 'experiencia' },
  { id: 479, text: `O Que Você Faria Se ___? Eu Acabei De Fazer.`, category: 'autoridade' },
  { id: 480, text: `Um filme imperdível para quem luta com ___!`, category: 'autoridade' },
  { id: 481, text: `Expondo meu segredo para (resultado desejado)`, category: 'revelacao' },
  { id: 482, text: `Já se perguntou por que [problema comum] persiste?`, category: 'curiosidade' },
  { id: 483, text: `Depois de [período de tempo], percebi que estava fazendo isso errado.`, category: 'autoridade' },
  { id: 484, text: `Você acredita que eu costumava evitar [algo]? Agora, é um divisor de águas. Veja por quê.`, category: 'urgencia' },
  { id: 485, text: `Veja como eu fiz [feito impressionante] em apenas [tempo].`, category: 'tutorial' },
  { id: 486, text: `Veja como superei [um grande desafio]…`, category: 'tutorial' },
  { id: 487, text: `Veja como transformei meu fracasso em sucesso.`, category: 'tutorial' },
  { id: 488, text: `Gastei R\\\\$100 em [produto/serviço], e aqui está minha avaliação honesta.`, category: 'autoridade' },
  { id: 489, text: `Passei um dia fazendo [atividade], e aqui está o que aprendi.`, category: 'autoridade' },
  { id: 490, text: `Passei uma semana fazendo [atividade], e aqui está o que descobri.`, category: 'autoridade' },
  { id: 491, text: `Passei x horas coletando (relacionado a nicho) de mais de 100 (relacionado a nicho)…`, category: 'autoridade' },
  { id: 492, text: `Não acredito que estou dizendo isso em voz alta, mas...`, category: 'autoridade' },
  { id: 493, text: `Nunca contei isso para ninguém antes, mas...`, category: 'revelacao' },
  { id: 494, text: `Perdi meu [NEGÓCIO, RELACIONAMENTO, LOCAL DE TRABALHO, ETC] [QUANTIDADE DE RECURSO VALIOSO COMO TEMPO, DINHEIRO, DOR, ETC]`, category: 'dor' },
  { id: 495, text: `O maior erro que já cometi foi...`, category: 'dor' },
  { id: 496, text: `Testei [método], e aqui está minha opinião honesta.`, category: 'experiencia' },
  { id: 497, text: `Tentei [método alternativo], e funcionou melhor do que [método tradicional].`, category: 'experiencia' },
  { id: 498, text: `Tentei [projeto faça você mesmo], e foi um divisor de águas.`, category: 'experiencia' },
  { id: 499, text: `Eu estava trabalhando em um [emprego] das 18h às 4h com apenas R\\\\$400 na minha conta bancária. Veja como eu reverti a situação.`, category: 'tutorial' },
  { id: 500, text: `Nunca esquecerei o dia em que [evento].`, category: 'autoridade' },
  { id: 501, text: `Nunca mais voltarei a ___ depois de aprender isso.`, category: 'autoridade' },
  { id: 502, text: `Vou te contar um segredo que ninguém jamais te contou sobre [conhecimento interno].`, category: 'revelacao' },
  { id: 503, text: `Estou prestes a revelar meu segredo sobre [tópico], mas nem me importo.`, category: 'revelacao' },
  { id: 504, text: `Eu não ia compartilhar isso, mas _____`, category: 'autoridade' },
  { id: 505, text: `Acho que acabei de encontrar ___`, category: 'autoridade' },
  { id: 506, text: `Chamando todos os ___ que estão cansados de ___`, category: 'dor' },
  { id: 507, text: `Se tem uma coisa que você nunca vai me pegar fazendo, é isso...`, category: 'autoridade' },
  { id: 508, text: `Ok, estou compartilhando meu segredo sobre como eu ___`, category: 'revelacao' },
  { id: 509, text: `Provavelmente vou receber muito ódio por isso, mas não me importo.`, category: 'autoridade' },
  { id: 510, text: `Tenho certeza que ninguém esperava por isso…`, category: 'revelacao' },
  { id: 511, text: `Fiquei maravilhado com essa descoberta.`, category: 'autoridade' },
  { id: 512, text: `Aqui está uma história sobre como eu [superei um desafio].`, category: 'historia' },
  { id: 513, text: `Aqui está o que aconteceu quando eu [tentei algo novo]...`, category: 'historia' },
  { id: 514, text: `Aqui está o que aconteceu quando acidentalmente fizemos isso.`, category: 'historia' },
  { id: 515, text: `Eu tentei [desafio], e os resultados me surpreenderam.`, category: 'experiencia' },
  { id: 516, text: `Não acredito que costumava ignorar [algo importante], mas agora eu juro por isso.`, category: 'urgencia' },
  { id: 517, text: `Eu fiz ___ por uma semana e aqui está o que aconteceu.`, category: 'historia' },
  { id: 518, text: `Eu me desafiei a [fazer algo difícil], e aqui está o que aconteceu…`, category: 'historia' },
  { id: 519, text: `Aceitando o [desafio popular]—terei sucesso?`, category: 'autoridade' },
  { id: 520, text: `A coisa mais louca acabou de acontecer em (lugar), você nunca vai acreditar.`, category: 'autoridade' },
  { id: 521, text: `O segredo sombrio por trás da [prática da indústria].`, category: 'revelacao' },
  { id: 522, text: `A única coisa que impulsionou meu [aspecto] instantaneamente.`, category: 'autoridade' },
  { id: 523, text: `Os resultados não foram o que eu esperava...`, category: 'autoridade' },
  { id: 524, text: `qual a coisa mais louca que você já fez por [tópico]?`, category: 'curiosidade' },
  { id: 525, text: `Por que não há mais pessoas falando sobre ___`, category: 'autoridade' },
  { id: 526, text: `Por que eu sempre [uso estratégia/produto] e você também deveria.`, category: 'autoridade' },
  { id: 527, text: `Por que eu acho que [algo amplamente aceito] está errado…`, category: 'autoridade' },
  { id: 528, text: `Você nunca mais olhará para ___ da mesma forma.`, category: 'autoridade' },
  { id: 529, text: `Você nunca vai adivinhar o que aconteceu quando tentei isso!`, category: 'historia' },
  { id: 530, text: `esta história é uma lição sobre por que…`, category: 'historia' },
  { id: 531, text: `este vídeo tem uma surpresa que você não verá chegando…`, category: 'autoridade' },
  { id: 532, text: `este vídeo vai me deixar rico… pelo menos… espero que sim.`, category: 'autoridade' },
  { id: 533, text: `assista-me tentar [uma tarefa aparentemente impossível]…`, category: 'autoridade' },
  { id: 534, text: `assista-me transformar [objeto/espaço] com apenas R\\\\$ 20.`, category: 'autoridade' },
  { id: 535, text: `assista-me transformar [algo] em apenas [período de tempo].`, category: 'autoridade' },
  { id: 536, text: `assista-me tentar [algo difícil] — spoiler: falhei espetacularmente…`, category: 'autoridade' },
  { id: 537, text: `assista atentamente — isto acontece rápido…`, category: 'urgencia' },
  { id: 538, text: `Esta é a história de como eu [conquistei algo notável]…`, category: 'historia' },
  { id: 539, text: `Este erro me custou R\\\\$ xxx. Veja o que aconteceu…`, category: 'dor' },
  { id: 540, text: `Este momento me ensinou uma lição valiosa…`, category: 'autoridade' },
  { id: 541, text: `Esta única mudança fez uma grande diferença.`, category: 'autoridade' },
  { id: 542, text: `Esta única mudança transformou minha [vida/saúde/finanças].`, category: 'autoridade' },
  { id: 543, text: `Este único hábito mudou minha vida.`, category: 'autoridade' },
  { id: 544, text: `Esta é a história de como eu [conquistei algo notável]…`, category: 'historia' },
  { id: 545, text: `Eu tive que comprar um desses [Mostrar o produto] DEIXE-ME EXPLICAR o que ele faz...`, category: 'autoridade' },
  { id: 546, text: `Ok, então isto (produto) está literalmente quebrando a internet...`, category: 'autoridade' },
  { id: 547, text: `A (Plataforma) acabou de lançar um novo recurso e estou super animado com isso! Deixe-me explicar.`, category: 'autoridade' },
  { id: 548, text: `Aqui está a RAZÃO REAL pela qual você não consegue atingir [objetivo]... e como consertar!`, category: 'tutorial' },
  { id: 549, text: `Semana Passada eu estava Fazendo ___ Quando ___ Aconteceu…`, category: 'historia' },
  { id: 550, text: `Minha Luta Pessoal Contra (x problema)`, category: 'autoridade' },
  { id: 551, text: `Eu experimentei todo (espaço em branco) para que você não precise`, category: 'experiencia' },
  { id: 552, text: `Veja o que eu pedi e veja o que eu recebi`, category: 'autoridade' },
  { id: 553, text: `*"Meu/Minha [pessoa/relação] me comprou este [produto/ferramenta], e mudou tudo."*`, category: 'autoridade' },
  { id: 554, text: `*"Eu spent [amount de tempo] em [processo], e aqui's o que Eu learned."*`, category: 'autoridade' },
  { id: 555, text: `*"o tempo Eu [específico evento]—e como isso transformed meu [vida/career/processo]."*`, category: 'tutorial' },
  { id: 556, text: `*"Aqui's um história sobre [comum struggle] e como Eu overcame isso."*`, category: 'historia' },
  { id: 557, text: `*"Let me pegar você back para quando Eu [específico moment/evento]."*`, category: 'historia' },
  { id: 558, text: `Meu maior arrependimento é não [action] antes.`, category: 'dor' },
  { id: 559, text: `POV: meu [friend/family] told me [algo important], e aqui's o que Eu encontrei.`, category: 'historia' },
  { id: 560, text: `Eu comprou isso [produto] para [alguém], e agora [resultado]!`, category: 'urgencia' },
  { id: 561, text: `[Personal situação] taught me isso uma coisa.`, category: 'autoridade' },
  { id: 562, text: `Eu dropped fora de college para chase meu dream de [objetivo].`, category: 'autoridade' },
  { id: 563, text: `POV: [describe relatable scenario].`, category: 'historia' },
  { id: 564, text: `meu [partner/friend/co-worker] surprised me com [indústria-related item/experience], aqui's o que's incrível sobre isso.`, category: 'autoridade' },
  { id: 565, text: `Eu dropped fora de [school/trabalho] para chase meu dream de [indústria-related objetivo].`, category: 'autoridade' },
  { id: 566, text: `como Eu saved [tempo/dinheiro/etc.] while ainda achieving [indústria objetivo].`, category: 'tutorial' },
  { id: 567, text: `Eu pode't obter sobre [indústria-related resultado ou experience].`, category: 'autoridade' },
  { id: 568, text: `POV: [situação] changed everything para me.`, category: 'historia' },
  { id: 569, text: `Let me tell você o história de como [situação] led para [resultado].`, category: 'historia' },
  { id: 570, text: `o uma coisa que eu queria ter sabido antes de starting em [indústria].`, category: 'autoridade' },
  { id: 571, text: `Aqui’s o moment Eu realized [lesson learned].`, category: 'autoridade' },
  { id: 572, text: `você won’t believe o que happened quando Eu tentou [action].`, category: 'historia' },
  { id: 573, text: `Eu era [struggling], mas then isso happened…`, category: 'autoridade' },
  { id: 574, text: `como Eu overcame [challenge] e built [resultado].`, category: 'tutorial' },
  { id: 575, text: `[Personal história] que vai mudar o jeito você pensar sobre [tópico].`, category: 'historia' },
  { id: 576, text: `Isso experience made me realize o importance de [lesson].`, category: 'autoridade' },
  { id: 577, text: `“deixa eu te contar uma história rápida sobre [evento].”`, category: 'historia' },
  { id: 578, text: `“Eu learned o difícil jeito quando Eu [experience].”`, category: 'historia' },
  { id: 579, text: `“Once upon um tempo, Eu faced [challenge]…”`, category: 'autoridade' },
  { id: 580, text: `“Isso é como Eu overcame meu biggest obstacle.”`, category: 'tutorial' },
  { id: 581, text: `“Aqui’s um história sobre o tempo Eu [memorable moment].”`, category: 'historia' },
  { id: 582, text: `“você won’t believe o que happened quando Eu [action].”`, category: 'historia' },
  { id: 583, text: `“Eu usou para lutam com [issue], e aqui’s como Eu fixed isso.”`, category: 'tutorial' },
  { id: 584, text: `“Isso experience changed meu vida forever.”`, category: 'autoridade' },
  { id: 585, text: `“Aqui’s o que happened quando Eu tentou [action].”`, category: 'historia' },
  { id: 586, text: `“Eu’ll nunca forget o dia Eu [evento].”`, category: 'autoridade' },
  { id: 587, text: `“Isso moment taught me um valuable lesson.”`, category: 'autoridade' },
  { id: 588, text: `“Aqui’s um funny história sobre [situação].”`, category: 'historia' },
  { id: 589, text: `“Isso é o que Eu wish Eu sabia quando Eu started [journey].”`, category: 'historia' },
  { id: 590, text: `“Let me share meu biggest regret com você.”`, category: 'autoridade' },
  { id: 591, text: `“Aqui’s como Eu turned meu failure em success.”`, category: 'tutorial' },
  { id: 592, text: `POV: meu friend surprised me com um crypto investment, aqui’s o que’s incrível sobre isso.`, category: 'historia' },
  { id: 593, text: `POV: como para pegar stunning nature photos.`, category: 'historia' },
  { id: 594, text: `Eu comprou isso parenting program para meu partner e agora nós’re em o same page com nosso parenting techniques.`, category: 'urgencia' },
  { id: 595, text: `Eu testei todo photo editing app fora there e aqui são o resultados…`, category: 'experiencia' },
  { id: 596, text: `Eu comprou isso tripod para meu girlfriend e agora ela’s taking o most incrível landscape shots!`, category: 'urgencia' },
  { id: 597, text: `Eu spent hours researching o melhor crypto investments e isso é o que Eu encontrei.`, category: 'autoridade' },
  { id: 598, text: `Eu dropped fora de college para chase meu dream de becoming um crypto millionaire.`, category: 'autoridade' },
  { id: 599, text: `Aqui's meu favorite lesson de (este ano).`, category: 'autoridade' },
  { id: 600, text: `como Eu went de [___] para [___] em (número de dias).`, category: 'tutorial' },
  { id: 601, text: `Eu pegou meu client de [___] para [___] by doing these (número) coisas.`, category: 'autoridade' },
  { id: 602, text: `se alguém tinha told me [insight], eu faria’ve nunca believed eles.`, category: 'autoridade' },
  { id: 603, text: `o quickest maneira de solve [___]`, category: 'autoridade' },
  { id: 604, text: `Isso é por que seu [___] não está funcionando`, category: 'dor' },
  { id: 605, text: `se você querer [___] avoid isso, e tente isso!`, category: 'autoridade' },
  { id: 606, text: `como para [___] em [___]`, category: 'tutorial' },
  { id: 607, text: `obter Rid de [___] com [___]`, category: 'autoridade' },
  { id: 608, text: `Isso um erro pode estar te custando [___]`, category: 'dor' },
  { id: 609, text: `Isso é por que seu [___] isn’t working`, category: 'curiosidade' },
  { id: 610, text: `Expondo meu segredo para [___]`, category: 'revelacao' },
  { id: 611, text: `pare de rolar se você sofre de [___]`, category: 'dor' },
  { id: 612, text: `Isso may trigger some de você mas ...`, category: 'autoridade' },
  { id: 613, text: `Este truque vai te economizar horas em [___]`, category: 'autoridade' },
  { id: 614, text: `se você’re não getting [___] then você need para ser doing [___]`, category: 'autoridade' },
  { id: 615, text: `Isso é por que seu [___] não está funcionando`, category: 'dor' },
  { id: 616, text: `Quer [___]? Então pare de rolar`, category: 'dor' },
  { id: 617, text: `como para [___] em [___]`, category: 'tutorial' },
  { id: 618, text: `Quer para sentir [___] mas não querer para break o bank?`, category: 'autoridade' },
  { id: 619, text: `o quickest maneira de solve [___]`, category: 'autoridade' },
  { id: 620, text: `se você querer [___] avoid isso, e tente isso!`, category: 'autoridade' },
  { id: 621, text: `fazer você ter problems com [___]? aqui's o solução!`, category: 'autoridade' },
  { id: 622, text: `são você struggling com [problema]? isso should solve seu problema!`, category: 'curiosidade' },
  { id: 623, text: `fazer você querer para aprender como para [habilidade] rápido?`, category: 'urgencia' },
  { id: 624, text: `ter você já senti like x?`, category: 'curiosidade' },
  { id: 625, text: `Por que você Should (Ação)`, category: 'autoridade' },
  { id: 626, text: `como para (resultado desejado) com não (Resources)`, category: 'tutorial' },
  { id: 627, text: `veja por que você keep failing at...`, category: 'autoridade' },
  { id: 628, text: `então você querer para [alcançar o objetivo] mas você keep getting stuck...Eu pensar Eu saber por que.`, category: 'autoridade' },
  { id: 629, text: `se você're struggling com [problema], watch isso.`, category: 'autoridade' },
  { id: 630, text: `se você está cansado de [problema específico], aqui's um solução.`, category: 'dor' },
  { id: 631, text: `isso apenas takes 5 minutes para [___]!`, category: 'autoridade' },
  { id: 632, text: `isso realmente doesn't ter para ser complicated. simplify seu [processo ou tarefa].`, category: 'autoridade' },
  { id: 633, text: `isso's mais fácil than você pensar para [___]!`, category: 'autoridade' },
  { id: 634, text: `mistakes você're probably making se você não está getting [resultado desejado].`, category: 'dor' },
  { id: 635, text: `parar doing (dor de público-alvo) agora mesmo! instead (resultado desejado).`, category: 'dor' },
  { id: 636, text: `parar wasting seu tempo com esse erro!`, category: 'dor' },
  { id: 637, text: `aqui's como para overcome challenges com [___].`, category: 'tutorial' },
  { id: 638, text: `aqui's como para solve [problema] em [prazo].`, category: 'tutorial' },
  { id: 639, text: `aqui's como para avoid [comum erro] quando [performing um tarefa].`, category: 'dor' },
  { id: 640, text: `veja como fazer seu [item] último longer.`, category: 'tutorial' },
  { id: 641, text: `eu encontrei o perfect solução para [problema].`, category: 'autoridade' },
  { id: 642, text: `Aqui’s como para avoid [comum erro]…`, category: 'dor' },
  { id: 643, text: `eu usou para lutam com [issue], e aqui’s como eu fixed isso.`, category: 'tutorial' },
  { id: 644, text: `eu usou para pensar ___, mas then eu learned…`, category: 'autoridade' },
  { id: 645, text: `eu era skeptical sobre [tendência], mas aqui's meu experience.`, category: 'autoridade' },
  { id: 646, text: `você ter para parar believing ___ se você querer _____`, category: 'autoridade' },
  { id: 647, text: `se você querer ___ avoid isso uma coisa`, category: 'autoridade' },
  { id: 648, text: `o easiest & most accessible maneira de obter started com ___`, category: 'autoridade' },
  { id: 649, text: `pare de rolar se você sofre de ___`, category: 'dor' },
  { id: 650, text: `o quickest maneira de solve ___`, category: 'autoridade' },
  { id: 651, text: `Isso é o biggest erro pessoas fazer quando ___`, category: 'dor' },
  { id: 652, text: `se você’re não doing ___ você’re missing fora`, category: 'autoridade' },
  { id: 653, text: `o Most Efficient maneira de ___ se você're ___…`, category: 'autoridade' },
  { id: 654, text: `como para obter ___ Quickly`, category: 'tutorial' },
  { id: 655, text: `se você querer ___ avoid isso, e tente isso!`, category: 'autoridade' },
  { id: 656, text: `Quer para sentir ___ mas não querer para break o bank?`, category: 'autoridade' },
  { id: 657, text: `Quer ___? Então pare de rolar`, category: 'dor' },
  { id: 658, text: `O que ___ indústria não querem que você saiba sobre ___`, category: 'autoridade' },
  { id: 659, text: `veja por que [comum belief] é um myth.`, category: 'autoridade' },
  { id: 660, text: `veja por que [comum belief] é misleading.`, category: 'autoridade' },
  { id: 661, text: `veja por que [comum produto] é overrated.`, category: 'autoridade' },
  { id: 662, text: `veja por que [popular advice] não está funcionando para você.`, category: 'dor' },
  { id: 663, text: `veja por que você're failing at [tarefa].`, category: 'autoridade' },
  { id: 664, text: `aqui's o que você need para saber antes trying [produto/serviço].`, category: 'autoridade' },
  { id: 665, text: `eu descobri [ferramenta], e isso revolutionized meu [tarefa].`, category: 'autoridade' },
  { id: 666, text: `eu followed [pessoa]'s routine para um semana, e aqui's o que happened.`, category: 'autoridade' },
  { id: 667, text: `Isso é meu most controversial belief sobre ___`, category: 'autoridade' },
  { id: 668, text: `se você're like me  like me & fazer ___, then isso um's para você`, category: 'autoridade' },
  { id: 669, text: `como para ___ em ___`, category: 'tutorial' },
  { id: 670, text: `como Eu __ while em um budget`, category: 'tutorial' },
  { id: 671, text: `o #1 maneira de fazer ___ …`, category: 'lista' },
  { id: 672, text: `último semana Eu era Doing ___ Quando ___ Happened…`, category: 'autoridade' },
  { id: 673, text: `Aqui’s um comum erro pessoas fazer com [tarefa].`, category: 'dor' },
  { id: 674, text: `o most effective [produto] você've nunca tentou.`, category: 'autoridade' },
  { id: 675, text: `o most fato surpreendente sobre [tópico].`, category: 'autoridade' },
  { id: 676, text: `o most valuable [habilidade] em [ano]—master isso e você'll [resultado]...`, category: 'autoridade' },
  { id: 677, text: `o hidden dangers de [comum produto/practice].`, category: 'autoridade' },
  { id: 678, text: `o melhor resources para [learning algo]...`, category: 'autoridade' },
  { id: 679, text: `Os usos mais surpreendentes para [produto].`, category: 'autoridade' },
  { id: 680, text: `A lição mais importante que aprendi sobre [tópico]...`, category: 'autoridade' },
  { id: 681, text: `O [técnica] mais eficaz para [tarefa].`, category: 'autoridade' },
  { id: 682, text: `Aqui está uma dica profissional para [resolver um problema].`, category: 'autoridade' },
  { id: 683, text: `Aqui está uma espiada nos bastidores de [processo/evento]...`, category: 'dor' },
  { id: 684, text: `Aqui está um rápido resumo de [tópico complexo]...`, category: 'urgencia' },
  { id: 685, text: `O que estudos [palavra envolvente] dizem sobre (tópico) durante (período de tempo)`, category: 'autoridade' },
  { id: 686, text: `Coisas [palavra envolvente] que apenas (seu público) entenderá`, category: 'autoridade' },
  { id: 687, text: `Qual é a melhor maneira de [resolver um problema]? Aqui está a minha opinião…`, category: 'autoridade' },
  { id: 688, text: `Qual é a sua opinião sobre [um tópico controverso]?`, category: 'autoridade' },
  { id: 689, text: `Por que [ação específica] é a chave para [alcançar um objetivo].`, category: 'autoridade' },
  { id: 690, text: `Por que 99% de [público-alvo] não [alcançam um objetivo específico].`, category: 'autoridade' },
  { id: 691, text: `Por que 99% dos e-mails frios não recebem respostas.`, category: 'autoridade' },
  { id: 692, text: `Você precisa ver isso para entender [processo].`, category: 'autoridade' },
  { id: 693, text: `Você provavelmente está pensando demais em ___.`, category: 'autoridade' },
  { id: 694, text: `Posso compartilhar um segredo com você?`, category: 'revelacao' },
  { id: 695, text: `Isso já aconteceu com você antes?`, category: 'historia' },
  { id: 696, text: `Quando foi a última vez que você _____?`, category: 'urgencia' },
  { id: 697, text: `Você quer saber por que nunca deve ________`, category: 'autoridade' },
  { id: 698, text: `E se eu lhe dissesse que {insira uma afirmação polarizadora} ...`, category: 'dor' },
  { id: 699, text: `Você já notou que [PESSOA FAMOSA NA SUA INDÚSTRIA][CARACTERÍSTICA, AÇÃO, TRAÇO]? Eis o porquê...`, category: 'curiosidade' },
  { id: 700, text: `Se você é um empreendedor no TikTok, tenho uma pergunta para você...`, category: 'dor' },
  { id: 701, text: `O que aconteceria se você acreditasse em (resultado desejável)?`, category: 'autoridade' },
  { id: 702, text: `Você tem a capacidade de (resultado desejável) sem (coisa indesejável)?`, category: 'autoridade' },
  { id: 703, text: `Você está cometendo este erro com [uma tarefa específica]?`, category: 'dor' },
  { id: 704, text: `já ask yourself, [pensou-provoking pergunta]?`, category: 'autoridade' },
  { id: 705, text: `fazer você saber who você spend o most tempo com em seu vida?`, category: 'autoridade' },
  { id: 706, text: `pode você guess por que isso [relacionado ao nicho] é outcompeting x y z?`, category: 'autoridade' },
  { id: 707, text: `Você consegue ver um diferença em [items]?`, category: 'autoridade' },
  { id: 708, text: `Quer saber como [achieve algo]?`, category: 'tutorial' },
  { id: 709, text: `Quer saber como dobrar suas economias este ano?`, category: 'tutorial' },
  { id: 710, text: `Você sabe o segredo para [alcançar algo]?`, category: 'revelacao' },
  { id: 711, text: `Aqui’s por que Eu disagree com [comum belief]…`, category: 'autoridade' },
  { id: 712, text: `Aqui’s por que Eu’ll nunca parar ___.`, category: 'autoridade' },
  { id: 713, text: `se você [faça isso], eu automatically assume [resultado desejado].`, category: 'autoridade' },
  { id: 714, text: `se você agree, hit o like button…`, category: 'autoridade' },
  { id: 715, text: `se você pode relate para isso, keep watching.`, category: 'autoridade' },
  { id: 716, text: `se você fazer x, você’re going para [negative resultado].`, category: 'autoridade' },
  { id: 717, text: `se você’re ainda [doing isso], eu’m begging você para listen para me…`, category: 'autoridade' },
  { id: 718, text: `se você’re sob (# de age) e você’re não x, preste atenção!`, category: 'autoridade' },
  { id: 719, text: `se você’ve já struggled com x, fazer x.`, category: 'autoridade' },
  { id: 720, text: `eu querer para ser extremely honest com você sobre [tópico].`, category: 'autoridade' },
  { id: 721, text: `eu era skeptical sobre [method], mas isso realmente funciona.`, category: 'autoridade' },
  { id: 722, text: `Aqui’s por que Eu stopped [prática comum].`, category: 'autoridade' },
  { id: 723, text: `Aqui’s por que Eu’m obsessed com [produto/tendência].`, category: 'autoridade' },
  { id: 724, text: `Aqui’s por que Eu’ll nunca ___ novamente.`, category: 'autoridade' },
  { id: 725, text: `se você’re thinking sobre [action], watch isso primeiro.`, category: 'autoridade' },
  { id: 726, text: `se você’re struggling com [problema], watch isso.`, category: 'autoridade' },
  { id: 727, text: `é isso apenas me, ou does [algo strange] happen para todo mundo?`, category: 'autoridade' },
  { id: 728, text: `é there anything worse than x?`, category: 'autoridade' },
  { id: 729, text: `let me saber em o comments o que você pensar…`, category: 'autoridade' },
  { id: 730, text: `let’s figure fora por que (dor para público-alvo)`, category: 'dor' },
  { id: 731, text: `let’s talk sobre overcoming mistakes eu made quando [situação ou activity].`, category: 'dor' },
  { id: 732, text: `como would você react se [algo surprising] happened?`, category: 'tutorial' },
  { id: 733, text: `como would você react se você could become fluent em um novo language em um meses?`, category: 'tutorial' },
  { id: 734, text: `Struggling com [dor de público-alvo]? Aqui’s um segredo dica Eu wish Eu sabia earlier.`, category: 'dor' },
  { id: 735, text: `o [pessoas em seu nicho] são going para odiar me para isso mas…`, category: 'autoridade' },
  { id: 736, text: `o real razão por trás [evento] might shock você.`, category: 'autoridade' },
  { id: 737, text: `o biggest segredo sobre [resultado desejado] não um shares.`, category: 'revelacao' },
  { id: 738, text: `o uma coisa você should nunca fazer quando [activity].`, category: 'autoridade' },
  { id: 739, text: `Which [category] resonates com você? um) [option um] ou B) [option b]?`, category: 'autoridade' },
  { id: 740, text: `Which side de [issue] são você em? um) [option um] ou B) [option b]?`, category: 'autoridade' },
  { id: 741, text: `Por que são você ainda [doing isso] em 2024?`, category: 'autoridade' },
  { id: 742, text: `Por que does não um talk sobre isso?`, category: 'autoridade' },
  { id: 743, text: `Você já passou por ___? Aqui’s como para nunca fazer que novamente …`, category: 'curiosidade' },
  { id: 744, text: `Isso may ser controversial mas ___`, category: 'autoridade' },
  { id: 745, text: `“e se eu te dissesse..” ( Finish isso fora )`, category: 'curiosidade' },
  { id: 746, text: `“Let’s fazer, Let’s ver..” ( Finish isso fora )`, category: 'autoridade' },
  { id: 747, text: `“Aqui’s como”.. ( Finish isso fora )`, category: 'tutorial' },
  { id: 748, text: `“você need para tente isso”`, category: 'autoridade' },
  { id: 749, text: `“fazer não fazer action antes você tente isso” ( show como para usar produto )`, category: 'tutorial' },
  { id: 750, text: `“Isso é por que Eu’ll nunca ir back para X”`, category: 'autoridade' },
  { id: 751, text: `X Mistakes você’re making com __`, category: 'dor' },
  { id: 752, text: `ter você heard sobre _ ?`, category: 'autoridade' },
  { id: 753, text: `___ pessoas pare de rolar!`, category: 'dor' },
  { id: 754, text: `Everything você sabia sobre ___ é 100% WRONG!`, category: 'curiosidade' },
  { id: 755, text: `(nicho) Preciso da sua ajuda por favor`, category: 'autoridade' },
  { id: 756, text: `Eu pode’t believe o que Eu apenas discovered!`, category: 'autoridade' },
  { id: 757, text: `se você like você need`, category: 'autoridade' },
  { id: 758, text: `Eu died quando Eu encontrei isso fora!`, category: 'historia' },
  { id: 759, text: `Eu ter algo para confess`, category: 'autoridade' },
  { id: 760, text: `"Isso é algo Eu wish Eu sabia quando starting fora em (nicho)"`, category: 'autoridade' },
  { id: 761, text: `"Eu realmente wish Eu sabia isso quando starting fora ( nicho )"`, category: 'autoridade' },
  { id: 762, text: `"dia em o vida de um (google employee ou smth) e fazer isso um troll vídeo"`, category: 'autoridade' },
  { id: 763, text: `"(isso produto é ótimo) mas stress won’t ajudar você usar isso right, aqui’s como você pode crack seu back e destress at home by yourself"`, category: 'tutorial' },
  { id: 764, text: `"Aqui’s um sleep dica que vai blow seu mind ( usar seu nicho somehow creatively )"`, category: 'autoridade' },
  { id: 765, text: `"5 Healthy coisas você pode fazer para improve seu vida agora mesmo"`, category: 'urgencia' },
  { id: 766, text: `"Quer para fazer seu home olhar expensive? Then preste atenção agora mesmo!"`, category: 'urgencia' },
  { id: 767, text: `"você don’t need (expensive produto) para solve ( dor)"`, category: 'dor' },
  { id: 768, text: `"Aqui’s meu 2 favorite products você need para tentar at Walmart ( include some random evento ou vídeo de um velho lady ou smth thats funny btw)"`, category: 'autoridade' },
  { id: 769, text: `"você’re probably using (produto) wrong, heres o correct jeito"`, category: 'autoridade' },
  { id: 770, text: `"se você’re em o (nicho indústria) você NEED isso ( produto) agora mesmo"`, category: 'urgencia' },
  { id: 771, text: `"como muito should você ser paying para (serviço)"`, category: 'tutorial' },
  { id: 772, text: `"3 free apps Eu usar para ajudar com (nicho)"`, category: 'autoridade' },
  { id: 773, text: `"Aqui’s algo realmente Important Eu wish Eu learned em negócio school"`, category: 'autoridade' },
  { id: 774, text: `3 grande Mistakes você’re Making Quando _`, category: 'lista' },
  { id: 775, text: `Calling all (público-alvo)`, category: 'autoridade' },
  { id: 776, text: `Isso é como Eu got (x)`, category: 'tutorial' },
  { id: 777, text: `Aqui são ___ dicas para obter rid de ___`, category: 'autoridade' },
  { id: 778, text: `você need para parar _, veja por que`, category: 'autoridade' },
  { id: 779, text: `você’ve heard pessoas dizer mas ter você tentou ?`, category: 'autoridade' },
  { id: 780, text: `Sick/Tired de _? Keep watching, trust me/você need isso`, category: 'autoridade' },
  { id: 781, text: `Isso feels illegal para saber: _`, category: 'autoridade' },
  { id: 782, text: `(celebridade name) offered para comprar meu produto para (outrageous preço)!`, category: 'autoridade' },
  { id: 783, text: `(celebridade name) comprou meu produto!`, category: 'autoridade' },
  { id: 784, text: `Aqui é um simples truque para ajudar você fazer _`, category: 'autoridade' },
  { id: 785, text: `você need isso produto em seu vida!`, category: 'autoridade' },
  { id: 786, text: `meu stepsis got stuck em o washing machine então Eu tinha para _`, category: 'autoridade' },
  { id: 787, text: `olhar who comprou meu produto! (show/name celebridade)`, category: 'autoridade' },
  { id: 788, text: `Eu met (controversial pessoa/celeb) e aqui’s o que eles disse _`, category: 'autoridade' },
  { id: 789, text: `POV: você realise (x)`, category: 'historia' },
  { id: 790, text: `Por que 99% de (audiência) won’t _`, category: 'autoridade' },
  { id: 791, text: `Eu wish Eu sabia sobre these (x) earlier`, category: 'autoridade' },
  { id: 792, text: `pare de rolar se você quer fazer ___`, category: 'dor' },
  { id: 793, text: `Eu apenas encontrei o perfect produto que helps com ___`, category: 'autoridade' },
  { id: 794, text: `vir com me para fazer ___`, category: 'autoridade' },
  { id: 795, text: `Aqui’s um simples truque para ajudar você fazer ___`, category: 'autoridade' },
  { id: 796, text: `fazer você ter problems com ___? Well Eu apenas encontrei o perfect solução!`, category: 'autoridade' },
  { id: 797, text: `Aqui’s como Eu achieved ___ em apenas (quantity) meses/anos!`, category: 'tutorial' },
  { id: 798, text: `Isso é o apenas coisa você need para saber sobre ___!`, category: 'autoridade' },
  { id: 799, text: `Don’t fazer isso erro quando doing ___`, category: 'dor' },
  { id: 800, text: `o que você faria se ___?`, category: 'autoridade' },
  { id: 801, text: `Por que does não um talk sobre isso?`, category: 'autoridade' },
  { id: 802, text: `se você querer ___, avoid doing isso!`, category: 'autoridade' },
  { id: 803, text: `Don’t believe isso ___ myth!`, category: 'autoridade' },
  { id: 804, text: `Other ___ são lying para você!`, category: 'autoridade' },
  { id: 805, text: `Isso ___ vai blow seu mind!`, category: 'autoridade' },
  { id: 806, text: `é isso apenas me, ou ___`, category: 'autoridade' },
  { id: 807, text: `você vai olhar at ___ differently by o end de isso vídeo!`, category: 'autoridade' },
  { id: 808, text: `Sudden Motion/Movement`, category: 'autoridade' },
  { id: 809, text: `_ Eu pode't obter enough de`, category: 'autoridade' },
  { id: 810, text: `“fazer não fazer action antes você tente isso” ( show como para usar produto )`, category: 'tutorial' },
  { id: 811, text: `“Isso é por que Eu’ll nunca ir back para X”`, category: 'autoridade' },
  { id: 812, text: `“Don’t comprar (expensive produto) quando você pode usar seu produto”`, category: 'autoridade' },
  { id: 813, text: `“3 razões por que X Won’t trabalhar”`, category: 'lista' },
  { id: 814, text: `“se você apenas started using produto você absolutely ter para ver isso”`, category: 'autoridade' },
  { id: 815, text: `“Isso é por que seu X isn’t working”`, category: 'curiosidade' },
  { id: 816, text: `“se você’re X preste atenção”`, category: 'autoridade' },
  { id: 817, text: `eu descobri o segredo para ___`, category: 'revelacao' },
  { id: 818, text: `você need para parar doing isso!`, category: 'autoridade' },
  { id: 819, text: `Você sabia que ___?`, category: 'curiosidade' },
  { id: 821, text: `você don’t querer para miss isso!`, category: 'autoridade' },
  { id: 822, text: `Don’t scroll!`, category: 'autoridade' },
  { id: 823, text: `Isso é um reminder para fazer ___`, category: 'autoridade' },
  { id: 824, text: `Isso é o história de ___`, category: 'historia' },
  { id: 825, text: `Este truque vai te economizar horas em ___`, category: 'autoridade' },
  { id: 826, text: `se você quer fazer ___, você need para faça isso!`, category: 'autoridade' },
  { id: 827, text: `para meu male/female audiência`, category: 'autoridade' },
  { id: 828, text: `se você like ____ você’re gonna like/odiar isso`, category: 'autoridade' },
  { id: 829, text: `o que's um piece de advice que sounds illegal___`, category: 'autoridade' },
  { id: 830, text: `O que eu pedi vs. o que eu recebi.`, category: 'autoridade' },
  { id: 831, text: `Red flags para olhar para em ___`, category: 'autoridade' },
  { id: 832, text: `5 mistakes você são probably making quando você [___]`, category: 'lista' },
  { id: 833, text: `tente isso um truque para obter [___]`, category: 'autoridade' },
  { id: 834, text: `Isso free ferramenta é um game changer!`, category: 'autoridade' },
  { id: 835, text: `Aqui são 3 signs que você should [___]`, category: 'autoridade' },
  { id: 836, text: `Isso um simples erro pode estar te custando [___]`, category: 'dor' },
  { id: 837, text: `Aqui’s meu ir-para [___] para [___]`, category: 'autoridade' },
  { id: 838, text: `o melhor [___] Eu’ve já usou!`, category: 'autoridade' },
  { id: 839, text: `Eu testei todo [___] então você don’t ter para!`, category: 'experiencia' },
  { id: 840, text: `5 coisas você pode fazer agora mesmo para improve [___]`, category: 'lista' },
  { id: 841, text: `você need isso free ferramenta para [___]`, category: 'autoridade' },
  { id: 842, text: `Isso é por que seu [___] isn’t working!`, category: 'curiosidade' },
  { id: 843, text: `Isso truque changed meu vida!`, category: 'autoridade' },
  { id: 844, text: `[___] like um Movie Star`, category: 'autoridade' },
  { id: 845, text: `[___] é o apenas um Eu usar para [___] e Eu'm gonna show você por que.`, category: 'autoridade' },
  { id: 846, text: `Predictions em o Future de [___]`, category: 'autoridade' },
  { id: 847, text: `# razões [___] é melhor que [___]`, category: 'autoridade' },
  { id: 848, text: `# razões [___] é o pior [___]`, category: 'autoridade' },
  { id: 849, text: `# razões isso's Better para [___]`, category: 'autoridade' },
  { id: 850, text: `obter em [___] em # fácil Minutes um dia`, category: 'autoridade' },
  { id: 851, text: `obter Paid para [___]!`, category: 'autoridade' },
  { id: 852, text: `“Aqui’s o melhor maneira de”`, category: 'autoridade' },
  { id: 853, text: `“Eu cant believe”`, category: 'autoridade' },
  { id: 854, text: `“3 jeitos você pode X”`, category: 'lista' },
  { id: 855, text: `“Watch o que happens quando X”`, category: 'autoridade' },
  { id: 856, text: `“Isso feels illegal para saber”`, category: 'autoridade' },
  { id: 857, text: `“Hoje eu descobri que”`, category: 'urgencia' },
  { id: 858, text: `“X revelado isso chocante novo data”`, category: 'revelacao' },
  { id: 859, text: `“se você querer X preste atenção”`, category: 'autoridade' },
  { id: 860, text: `“Eu bet você didn’t saber X”`, category: 'autoridade' },
  { id: 861, text: `“Aqui’s uma coisa stopping você de dor/insecurity”`, category: 'dor' },
  { id: 862, text: `“Eu usou para sentir dor until Eu realized Y”`, category: 'dor' },
  { id: 863, text: `obter Rid de seu [___] Once e para All`, category: 'curiosidade' },
  { id: 864, text: `OMG você won’t believe isso`, category: 'autoridade' },
  { id: 866, text: `por favor parar trying para [___]`, category: 'autoridade' },
  { id: 867, text: `POV você apenas comprou isso`, category: 'historia' },
  { id: 868, text: `se você’re não doing isso, você’re missing fora`, category: 'autoridade' },
  { id: 869, text: `é isso too bom para ser verdade?`, category: 'autoridade' },
  { id: 870, text: `comprar isso antes isso's gone`, category: 'autoridade' },
  { id: 871, text: `se você [___] preste atenção`, category: 'autoridade' },
  { id: 872, text: `Winter é coming você need isso [___]`, category: 'autoridade' },
  { id: 873, text: `# razões não para [___]`, category: 'autoridade' },
  { id: 874, text: `como para fazer certeza você'll nunca [___]`, category: 'tutorial' },
  { id: 875, text: `Suppose Isso Happened…`, category: 'autoridade' },
  { id: 876, text: `Instead de doing/using [___] fazer [___].`, category: 'autoridade' },
  { id: 877, text: `antes você scroll [___]`, category: 'autoridade' },
  { id: 878, text: `Eu spent [___] anos designing isso`, category: 'autoridade' },
  { id: 879, text: `Products em o website vs real vida`, category: 'autoridade' },
  { id: 880, text: `Unpopular opinion:`, category: 'autoridade' },
  { id: 881, text: `____ fácil para remember dicas para _____`, category: 'autoridade' },
  { id: 882, text: `Você sabia _____ apenas blew para cima em popularity?`, category: 'curiosidade' },
  { id: 883, text: `se você fazer ____ você need para hear isso!!`, category: 'autoridade' },
  { id: 884, text: `“Got X problema?”`, category: 'autoridade' },
  { id: 885, text: `“Top 3 dicas sobre X”`, category: 'lista' },
  { id: 886, text: `“como para obter Y em 24 Hours”`, category: 'tutorial' },
  { id: 887, text: `“Por que ninguém está falando sobre Y”`, category: 'revelacao' },
  { id: 888, text: `“Aqui’s X tiny dicas que pode ajudar você achieve Y”`, category: 'autoridade' },
  { id: 889, text: `“Random coisas em meu apartment que apenas fazer sense”`, category: 'autoridade' },
  { id: 890, text: `“Eu wish Eu tinha Y earlier”`, category: 'autoridade' },
  { id: 891, text: `“Don’t fazer isso erro se você’re using X”`, category: 'dor' },
  { id: 892, text: `“Aqui’s um realmente powerful maneira de.. ( finish isso fora )`, category: 'autoridade' },
  { id: 893, text: `“Isso é um reminder para fazer..” ( finish isso fora )`, category: 'autoridade' },
  { id: 894, text: `“um huge realization Eu tinha sobre Y e aqui’s por que”`, category: 'autoridade' },
  { id: 895, text: `“X vai save você hours”`, category: 'autoridade' },
  { id: 896, text: `“Isso trick vai save você hours”`, category: 'autoridade' },
  { id: 897, text: `“Isso é como você pode obter Y em 30 dias”`, category: 'tutorial' },
  { id: 898, text: `“Aqui’s o verdade sobre XYZ grande companies don’t querer você para saber”`, category: 'autoridade' },
  { id: 899, text: `Quer para saber o segredo para ____?`, category: 'revelacao' },
  { id: 900, text: `Unpopular opinion... (X statement)`, category: 'autoridade' },
  { id: 901, text: `pare de rolar se você suffer com X`, category: 'dor' },
  { id: 902, text: `Eu pode’t believe isso happened…`, category: 'autoridade' },
  { id: 903, text: `Aviso para [alvo market]`, category: 'autoridade' },
  { id: 904, text: `fazer seu X olhar like isso...`, category: 'autoridade' },
  { id: 905, text: `"Aqui’s como Eu saved 30 dias este ano com isso simples ferramenta"`, category: 'tutorial' },
  { id: 906, text: `"(número) (nicho/negócio) tricks você didn’t saber were sendo usou em você"`, category: 'curiosidade' },
  { id: 907, text: `Isso single important dica vai mudar sua vida:`, category: 'autoridade' },
  { id: 908, text: `Eu nunca leave o house without ____`, category: 'autoridade' },
  { id: 909, text: `Eu era atheist antes Eu encontrei ____`, category: 'autoridade' },
  { id: 910, text: `"3 razões por que ( wrong solução ) wont trabalhar"`, category: 'lista' },
  { id: 911, text: `"o #1 coisa Eu tell todo customer/client/sales agent etc."`, category: 'lista' },
  { id: 912, text: `"Quer para Triple seu (resultado) em (platform/place)? Isso é como você fazer isso em 15 seconds."`, category: 'curiosidade' },
  { id: 913, text: `"Most (nicho/businesses) wont tell você these 5 secrets"`, category: 'autoridade' },
  { id: 914, text: `POV: ______`, category: 'historia' },
  { id: 915, text: `meu gf/bf apenas _____`, category: 'autoridade' },
  { id: 916, text: `Maturing é realizing ____`, category: 'autoridade' },
  { id: 917, text: `Aqui é por que ____`, category: 'autoridade' },
  { id: 918, text: `"Most (nicho/businesses) wont tell você isso"`, category: 'autoridade' },
  { id: 919, text: `"Aqui’s um poucos dicas que saved me loads de dinheiro em (beauty/dental produto etc.)"`, category: 'autoridade' },
  { id: 920, text: `"Eu não saber who needs para hear isso mas você’re probably (action) using (nicho/produto) wrong. Let me tell você por que (( para isso muitos words talk faster than usual ))"`, category: 'historia' },
  { id: 921, text: `Eu promise você’ve nunca X`, category: 'autoridade' },
  { id: 922, text: `obter seu GF/BF um ____`, category: 'autoridade' },
  { id: 923, text: `se você sofre de X`, category: 'dor' },
  { id: 924, text: `Trying o viral _`, category: 'autoridade' },
  { id: 925, text: `Você sabia…`, category: 'curiosidade' },
  { id: 926, text: `Aqui é um dica de um profissional ____ que pode ____`, category: 'autoridade' },
  { id: 927, text: `Aqui é o número #1 coisa [___] should saber`, category: 'lista' },
  { id: 928, text: `então isso apenas happened at [___]`, category: 'autoridade' },
  { id: 929, text: `Aqui’s como Eu did [___] em [___] (amount de tempo)`, category: 'tutorial' },
  { id: 931, text: `Por que ninguém está falando sobre [___]?`, category: 'revelacao' },
  { id: 932, text: `Eu comprou [___] então você don’t ter para`, category: 'autoridade' },
  { id: 933, text: `Isso é por que seu [___] isn’t working`, category: 'curiosidade' },
  { id: 934, text: `Aqui’s o que school doesn’t ensinar você:`, category: 'autoridade' },
  { id: 935, text: `[___] tricks experts não dare tell você (mas nós vai)`, category: 'autoridade' },
  { id: 936, text: `o ugly verdade sobre [___]`, category: 'autoridade' },
  { id: 937, text: `"Eu comprou o most expensive (produto) em (nicho) então você don’t ter para ( guys comprar isso e return isso lol )"`, category: 'autoridade' },
  { id: 938, text: `"Aqui’s um comum (dor) você need para avoid ( check part 2 para o resposta) send link em comments mas don/t dizer its there"`, category: 'dor' },
  { id: 939, text: `"Aqui’s um comum (dor) solução que vai blow seu point"`, category: 'dor' },
  { id: 940, text: `"Aqui’s como Eu solved ( problema) em (número de dias) com isso um simples trick"`, category: 'tutorial' },
  { id: 941, text: `"Save isso vídeo para o próximo tempo você need para (action)"`, category: 'autoridade' },
  { id: 942, text: `meu brother’s cousin’s sister’s boyfriend apenas [___]`, category: 'autoridade' },
  { id: 943, text: `Aqui’s por que [___] won’t trabalhar`, category: 'autoridade' },
  { id: 944, text: `o feminine/masculine urge para [___]`, category: 'autoridade' },
  { id: 945, text: `o pior coisas para fazer antes [___]`, category: 'autoridade' },
  { id: 946, text: `"Aqui’s um estranho indústria segredo eles’ve nunca told você sobre"`, category: 'revelacao' },
  { id: 947, text: `"Aqui’s um hot pegar em (nicho)"`, category: 'autoridade' },
  { id: 948, text: `"meu hot pegar em (nicho)"`, category: 'autoridade' },
  { id: 949, text: `"Aqui’s 5 coisas você’re going para fazer para ter ( problema solved ) isso meses"`, category: 'lista' },
  { id: 950, text: `"Avoid these 3 coisa’s se você’re trying para ( objetivo )"`, category: 'lista' },
  { id: 951, text: `você guys keep asking para ___`, category: 'autoridade' },
  { id: 952, text: `POV você apenas comprou isso`, category: 'historia' },
  { id: 953, text: `você won’t believe [____]`, category: 'autoridade' },
  { id: 954, text: `[____] coisas que eu queria ter sabido antes Eu [_____]`, category: 'autoridade' },
  { id: 955, text: `como Eu got [___] em 24 hours`, category: 'tutorial' },
];
